var u13 = [

{
code: "c1",
name: "bai 1",
audiourl: './audio/cd2/39 Track 39.mp3',
cotent: [`<div class="boxtv"><div class="tuvung">1091. <b>さっぱり</b></div><div class="hanviet3">   </div>

<div class="nghia3">hoàn toàn, thoải mái, nhẹ bỗng</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>早<rp>（</rp><rt>はや</rt><rp>）</rp></ruby>くシャワーを<ruby>浴<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>びて、さっぱりしたい。</div><div class="nghiavidu">Nhanh nhanh muốn đi tắm sảng khoái trở lại.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>部屋<rp>（</rp><rt>へや</rt><rp>）</rp></ruby>が<ruby>片付<rp>（</rp><rt>かたづ</rt><rp>）</rp></ruby>くと、さっぱりした<ruby>気分<rp>（</rp><rt>きぶん</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Nếu dọn dẹp phòng thì tâm trạng sẽ sảng khoái.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>日本人<rp>（</rp><rt>にほんじん</rt><rp>）</rp></ruby>はさっぱりした<ruby>料理<rp>（</rp><rt>りょうり</rt><rp>）</rp></ruby>を<ruby>好<rp>（</rp><rt>この</rt><rp>）</rp></ruby>む<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>が<ruby>多<rp>（</rp><rt>おお</rt><rp>）</rp></ruby>い。</div><div class="nghiavidu">Nhiều người Nhật thích món ăn vị nhạt.</div><br><div class="tuvung"><div class="viduseq">4.</div> <ruby>山野<rp>（</rp><rt>やまの</rt><rp>）</rp></ruby>さんは<ruby>性格<rp>（</rp><rt>せいかく</rt><rp>）</rp></ruby>がさっぱりしている。</div><div class="nghiavidu">Anh Yamano có tính cách thoải mái.</div><br><div class="tuvung"><div class="viduseq">5.</div> <ruby>今日<rp>（</rp><rt>きょう</rt><rp>）</rp></ruby>の<ruby>先生<rp>（</rp><rt>せんせい</rt><rp>）</rp></ruby>の<ruby>話<rp>（</rp><rt>はなし</rt><rp>）</rp></ruby>は<ruby>難<rp>（</rp><rt>むずか</rt><rp>）</rp></ruby>しくて、さっぱりわからなかった。</div><div class="nghiavidu">Câu chuyện hôm qua của thầy giáo khó, tôi không hiểu được toàn bộ.</div><br><div class="tuvung"><div class="viduseq">6.</div> 「<ruby>商売<rp>（</rp><rt>しょうばい</rt><rp>）</rp></ruby>/<ruby>仕事<rp>（</rp><rt>しごと</rt><rp>）</rp></ruby>/<ruby>勉強<rp>（</rp><rt>べんきょう</rt><rp>）</rp></ruby>…｝はどうですか」「さっぱりです」</div><div class="nghiavidu">"Buôn bán/ công việc/ học hành thế nào ạ?""Cũng tạm ạ"</div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>全<rp>（</rp><rt>まった</rt><rp>）</rp></ruby>く、<ruby>少<rp>（</rp><rt>すこ</rt><rp>）</rp></ruby>しも、<ruby>全然<rp>（</rp><rt>ぜんぜん</rt><rp>）</rp></ruby></div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1092. <b>すっきり</b></div><div class="hanviet3">   </div>

<div class="nghia3">khoan khoái, sảng khoái, dễ chịu</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>眠<rp>（</rp><rt>ねむ</rt><rp>）</rp></ruby>かったが、<ruby>顔<rp>（</rp><rt>かお</rt><rp>）</rp></ruby>を<ruby>洗<rp>（</rp><rt>あら</rt><rp>）</rp></ruby>うとすっきりした。</div><div class="nghiavidu">Buồn ngủ nhưng rửa mặt thì tỉnh táo ngay.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>悩<rp>（</rp><rt>なや</rt><rp>）</rp></ruby>みが<ruby>解決<rp>（</rp><rt>かいけつ</rt><rp>）</rp></ruby>して、すっきりした<ruby>気分<rp>（</rp><rt>きぶん</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Giải quyết được mối lo âu, cảm thấy thoải mái.</div><br><div class="tuvung"><div class="viduseq">3.</div> すっきりした｛デザイン/<ruby>部屋<rp>（</rp><rt>へや</rt><rp>）</rp></ruby>/<ruby>文章<rp>（</rp><rt>ぶんしょう</rt><rp>）</rp></ruby>…｝</div><div class="nghiavidu"></div><br><div class="tuvung"><span class="lienquan">関</span> さっぱり、シンプル</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1093. <b><ruby>実<rp>（</rp><rt>じつ</rt><rp>）</rp></ruby>に</b></div><div class="hanviet3">thực   </div>

<div class="nghia3">thực ra, thực tế</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> この<ruby>小説<rp>（</rp><rt>しょうせつ</rt><rp>）</rp></ruby>は<ruby>実<rp>（</rp><rt>じつ</rt><rp>）</rp></ruby>に<ruby>面白<rp>（</rp><rt>おもしろ</rt><rp>）</rp></ruby>かった。</div><div class="nghiavidu">Cuốn tiểu thuyết này thực sự rất thú vị.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「<ruby>実<rp>（</rp><rt>じつ</rt><rp>）</rp></ruby>に<ruby>素晴<rp>（</rp><rt>すば</rt><rp>）</rp></ruby>らしい！」</div><div class="nghiavidu">Thật là tuyệt vời!</div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>本当<rp>（</rp><rt>ほんとう</rt><rp>）</rp></ruby>に、<ruby>全<rp>（</rp><rt>まった</rt><rp>）</rp></ruby>く</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1094. <b><ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>い<ruby>切<rp>（</rp><rt>き</rt><rp>）</rp></ruby>り</b></div><div class="hanviet3">tư thiết  </div>

<div class="nghia3">hết mình, hết sức, quyết trí</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>試験<rp>（</rp><rt>しけん</rt><rp>）</rp></ruby>が<ruby>終<rp>（</rp><rt>お</rt><rp>）</rp></ruby>わったら、<ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>い<ruby>切<rp>（</rp><rt>き</rt><rp>）</rp></ruby>り<ruby>遊<rp>（</rp><rt>あそ</rt><rp>）</rp></ruby>びたい。</div><div class="nghiavidu">Kì thi kết thúc tôi muốn chơi hết mình.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>いっきり<ruby>力<rp>（</rp><rt>ちから</rt><rp>）</rp></ruby>を<ruby>入<rp>（</rp><rt>い</rt><rp>）</rp></ruby>れて<ruby>投<rp>（</rp><rt>な</rt><rp>）</rp></ruby>げたつもりだったが、ボールは<ruby>遠<rp>（</rp><rt>とお</rt><rp>）</rp></ruby>くまで<ruby>飛<rp>（</rp><rt>と</rt><rp>）</rp></ruby>ばなかった。</div><div class="nghiavidu">Đã cố gắng hết sức ném đi rồi nhưng bóng không bay được xa.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>才能<rp>（</rp><rt>さいのう</rt><rp>）</rp></ruby>がないと<ruby>分<rp>（</rp><rt>わ</rt><rp>）</rp></ruby>かったので、<ruby>画家<rp>（</rp><rt>がか</rt><rp>）</rp></ruby>になる<ruby>夢<rp>（</rp><rt>ゆめ</rt><rp>）</rp></ruby>は<ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>い<ruby>切<rp>（</rp><rt>き</rt><rp>）</rp></ruby>りよくあきらめた。</div><div class="nghiavidu">Tôi hiểu là không có tài năng, nên đã dứt khoát từ bỏ ước mơ trở thành họa sĩ.</div><br><div class="tuvung"><span class="lienquan">連</span> ＿がいい＜＝＞<ruby>悪<rp>（</rp><rt>わる</rt><rp>）</rp></ruby>い</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1095. <b><ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>と<ruby>無<rp>（</rp><rt>な</rt><rp>）</rp></ruby>く</b></div><div class="hanviet3">hà vô  </div>

<div class="nghia3">không hiểu sao, không có lý do</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>今日<rp>（</rp><rt>きょう</rt><rp>）</rp></ruby>は<ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>となくいいことがありそうな<ruby>気<rp>（</rp><rt>き</rt><rp>）</rp></ruby>がする。</div><div class="nghiavidu">Không hiểu sao hôm nay tôi cảm thấy có điều gì tốt.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>最近<rp>（</rp><rt>さいきん</rt><rp>）</rp></ruby><ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>となく<ruby>気分<rp>（</rp><rt>きぶん</rt><rp>）</rp></ruby>が<ruby>沈<rp>（</rp><rt>しず</rt><rp>）</rp></ruby>んで、<ruby>勉強<rp>（</rp><rt>べんきょう</rt><rp>）</rp></ruby>する<ruby>気<rp>（</rp><rt>き</rt><rp>）</rp></ruby>になれない。</div><div class="nghiavidu">Không hiểu sao gần đây tâm trạng không tốt, không muốn học hành.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1096. <b><ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>だか</b></div><div class="hanviet3">hà   </div>

<div class="nghia3">hơi hơi, 1 chút</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> なんだか<ruby>寒気<rp>（</rp><rt>さむけ</rt><rp>）</rp></ruby>がする、<ruby>風邪<rp>（</rp><rt>かぜ</rt><rp>）</rp></ruby>を<ruby>引<rp>（</rp><rt>ひ</rt><rp>）</rp></ruby>いたのだろうか。</div><div class="nghiavidu">Cảm thấy hơi lạnh sống lưng chút, bị cảm hay sao đây.</div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1097. <b>どうにか</b></div><div class="hanviet3">   </div>

<div class="nghia3">bằng cách nào đó, cuối cùng cũng…</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>家<rp>（</rp><rt>いえ</rt><rp>）</rp></ruby>から<ruby>走<rp>（</rp><rt>はし</rt><rp>）</rp></ruby>り<ruby>続<rp>（</rp><rt>つづ</rt><rp>）</rp></ruby>け、どうにか7<ruby>時<rp>（</rp><rt>じ</rt><rp>）</rp></ruby>の<ruby>電車<rp>（</rp><rt>でんしゃ</rt><rp>）</rp></ruby>に<ruby>間<rp>（</rp><rt>ま</rt><rp>）</rp></ruby>に<ruby>合<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>った。</div><div class="nghiavidu">Từ nhà cứ chạy liên tục nhờ thế mà đã kịp chuyến xe điện 7 giờ.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「お<ruby>宅<rp>（</rp><rt>たく</rt><rp>）</rp></ruby>の<ruby>犬<rp>（</rp><rt>いぬ</rt><rp>）</rp></ruby>の<ruby>鳴<rp>（</rp><rt>な</rt><rp>）</rp></ruby>き<ruby>声<rp>（</rp><rt>ごえ</rt><rp>）</rp></ruby>、どうにかなりませんか」</div><div class="nghiavidu">Tiếng kêu của con chó nhà mình, có cách nào đó không?</div><br><div class="tuvung"><span class="lienquan">類</span> なんとか</div><div class="nghiavidu"></div><br><div class="tuvung"><span class="lienquan">連</span> ＿なる、＿する、＿して</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1098. <b>どうにも</b></div><div class="hanviet3">   </div>

<div class="nghia3">chẳng thể làm gì</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>助<rp>（</rp><rt>たす</rt><rp>）</rp></ruby>けてあげたかったが、<ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>の<ruby>力<rp>（</rp><rt>ちから</rt><rp>）</rp></ruby>ではどうにもできなかった。</div><div class="nghiavidu">Tôi cũng muốn giúp đỡ nhưng với thể lực này thì tôi không thể làm gì cả.</div><div class="vidunotfirst"><br><div class="tuvung"><span class="lienquan">連</span> ＿ならない、＿できない</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1099. <b><ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>とか</b></div><div class="hanviet3">hà   </div>

<div class="nghia3">dù thế nào đi nữa</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>必死<rp>（</rp><rt>ひっし</rt><rp>）</rp></ruby>に<ruby>頑張<rp>（</rp><rt>がんば</rt><rp>）</rp></ruby>って、<ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>とか<ruby>合格<rp>（</rp><rt>ごうかく</rt><rp>）</rp></ruby>することができた。</div><div class="nghiavidu">Quyết tâm cố gắng, nhờ thế mà đã đậu được.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「この<ruby>時計<rp>（</rp><rt>とけい</rt><rp>）</rp></ruby>、どうしても<ruby>直<rp>（</rp><rt>なお</rt><rp>）</rp></ruby>してもらいたいんです。<ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>とかなりませんか」</div><div class="nghiavidu">Dù thế nào tôi cũng sửa cái đồng hồ này, có cách nào không ạ?</div><br><div class="tuvung"><div class="viduseq">3.</div> 「さっき、にし<ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>とかさんから<ruby>電話<rp>（</rp><rt>でんわ</rt><rp>）</rp></ruby>がありましたよ」「<ruby>西村<rp>（</rp><rt>にしむら</rt><rp>）</rp></ruby>さんかなあ」</div><div class="nghiavidu">"Vừa nãy có chị Nishi gì đó gọi đến đấy ạ.""Chị Nishimura à"</div><br><div class="tuvung"><div class="viduseq">4.</div> 「<ruby>黙<rp>（</rp><rt>だま</rt><rp>）</rp></ruby>ってないで、<ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>とか<ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>いなさい」</div><div class="nghiavidu">Đừng im lặng nữa, dù gì hãy nói đi!</div><br><div class="tuvung"><span class="lienquan">類</span> どうにか</div><div class="nghiavidu"></div><br><div class="tuvung"><span class="lienquan">連</span> ＿なる、＿する、＿して</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1100. <b><ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>とも</b></div><div class="hanviet3">hà   </div>

<div class="nghia3">không...một chút nào</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>をいじめた<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>を、<ruby>前<rp>（</rp><rt>まえ</rt><rp>）</rp></ruby>は<ruby>恨<rp>（</rp><rt>うら</rt><rp>）</rp></ruby>んでいたが、<ruby>今<rp>（</rp><rt>いま</rt><rp>）</rp></ruby>は<ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>とも<ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>っていない。</div><div class="nghiavidu">Trước đây tôi rất ghét người đã bắt nạt tôi, nhưng giờ thì không nghĩ ngợi gì.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>同<rp>（</rp><rt>おな</rt><rp>）</rp></ruby>じものを<ruby>食<rp>（</rp><rt>た</rt><rp>）</rp></ruby>べて、<ruby>弟<rp>（</rp><rt>おとうと</rt><rp>）</rp></ruby>はお<ruby>腹<rp>（</rp><rt>なか</rt><rp>）</rp></ruby>を<ruby>壊<rp>（</rp><rt>こわ</rt><rp>）</rp></ruby>したが、<ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>は<ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>ともなかった。</div><div class="nghiavidu">Ăn một thứ giống nhau nhưng em tôi thì bị đau bụng còn tôi thì không bị gì.</div><br><div class="tuvung"><div class="viduseq">3.</div> その<ruby>肉<rp>（</rp><rt>にく</rt><rp>）</rp></ruby>は<ruby>何<rp>（</rp><rt>なん</rt><rp>）</rp></ruby>とも<ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>えない<ruby>匂<rp>（</rp><rt>にお</rt><rp>）</rp></ruby>いがした。ちょっと<ruby>古<rp>（</rp><rt>ふる</rt><rp>）</rp></ruby>かったらしい。</div><div class="nghiavidu">Miếng thịt đó không thể nói gì là có mui. Chắc là thịt cũ.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1101. <b><ruby>態<rp>（</rp><rt>わざ</rt><rp>）</rp></ruby>と</b></div><div class="hanviet3">thái   </div>

<div class="nghia3">cố ý</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>子供<rp>（</rp><rt>こども</rt><rp>）</rp></ruby><ruby>相手<rp>（</rp><rt>あいて</rt><rp>）</rp></ruby>にゲームをするときは、<ruby>時々<rp>（</rp><rt>ときどき</rt><rp>）</rp></ruby>わざと<ruby>負<rp>（</rp><rt>ま</rt><rp>）</rp></ruby>けてやったりする。</div><div class="nghiavidu">Chơi game với đối thủ là con nít, đôi khi tôi cố ý thua.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>彼女<rp>（</rp><rt>かのじょ</rt><rp>）</rp></ruby>とは<ruby>話<rp>（</rp><rt>はな</rt><rp>）</rp></ruby>したくなかったので、わざと<ruby>気<rp>（</rp><rt>き</rt><rp>）</rp></ruby>が<ruby>付<rp>（</rp><rt>つ</rt><rp>）</rp></ruby>かないふりをした。</div><div class="nghiavidu">Tôi không muốn nói chuyện với cô ấy nên cố tình giả vờ không bận tâm.</div><br><div class="tuvung"><div class="viduseq">3.</div> あの<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>はときどきわざと<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>を<ruby>怒<rp>（</rp><rt>おこ</rt><rp>）</rp></ruby>らせる、<ruby>悪<rp>（</rp><rt>わる</rt><rp>）</rp></ruby>い<ruby>癖<rp>（</rp><rt>くせ</rt><rp>）</rp></ruby>がある。</div><div class="nghiavidu">Người ấy có thói quen xấu đôi khi cố tình chọc người khác nổi giận.</div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>故意<rp>（</rp><rt>こい</rt><rp>）</rp></ruby>に</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1102. <b><ruby>態々<rp>（</rp><rt>わざわざ</rt><rp>）</rp></ruby></b></div><div class="hanviet3">thái   </div>

<div class="nghia3">làm phiền, gây phiền</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>学校<rp>（</rp><rt>がっこう</rt><rp>）</rp></ruby>の<ruby>欠席<rp>（</rp><rt>けっせき</rt><rp>）</rp></ruby>をしたら、クラスメートがわざわざ<ruby>宿題<rp>（</rp><rt>しゅくだい</rt><rp>）</rp></ruby>をうちまで<ruby>届<rp>（</rp><rt>とど</rt><rp>）</rp></ruby>けてくれた。</div><div class="nghiavidu">Nghỉ học nên đứa bạn cất công gửi bài tập đến nhà cho tôi.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> わざわざ<ruby>遠<rp>（</rp><rt>とお</rt><rp>）</rp></ruby>くのデパート<ruby>行<rp>（</rp><rt>い</rt><rp>）</rp></ruby>って<ruby>買<rp>（</rp><rt>か</rt><rp>）</rp></ruby>ったのに、<ruby>同<rp>（</rp><rt>おな</rt><rp>）</rp></ruby>じものが<ruby>近所<rp>（</rp><rt>きんじょ</rt><rp>）</rp></ruby>のスーパーにもあった。</div><div class="nghiavidu">Cất công đến siêu thị xa tít mua đồ nhưng cũng giống hàng có ở siêu thị gần nhà.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1103. <b><ruby>折角<rp>（</rp><rt>せっかく</rt><rp>）</rp></ruby></b></div><div class="hanviet3">chiết giác  </div>

<div class="nghia3">đã mất công</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> せっかく<ruby>都心<rp>（</rp><rt>としん</rt><rp>）</rp></ruby>の<ruby>美術館<rp>（</rp><rt>びじゅつかん</rt><rp>）</rp></ruby>まで<ruby>行<rp>（</rp><rt>い</rt><rp>）</rp></ruby>ったのに、<ruby>満員<rp>（</rp><rt>まんいん</rt><rp>）</rp></ruby>で<ruby>入<rp>（</rp><rt>はい</rt><rp>）</rp></ruby>れなかった。</div><div class="nghiavidu">Cất công đến viện bảo tàng thành phố nhưng đông quá không thể vào được.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> せっかくのチャンスを<ruby>逃<rp>（</rp><rt>のが</rt><rp>）</rp></ruby>してしまった。</div><div class="nghiavidu">Đã bỏ lỡ cơ hội tốt.</div><br><div class="tuvung"><div class="viduseq">3.</div> せっかく<ruby>帰省<rp>（</rp><rt>きせい</rt><rp>）</rp></ruby>したのだから、<ruby>昔<rp>（</rp><rt>むかし</rt><rp>）</rp></ruby>の<ruby>友人<rp>（</rp><rt>ゆうじん</rt><rp>）</rp></ruby>たちにも<ruby>会<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>っていこう。</div><div class="nghiavidu">Đã cất công về quê rồi nên cố gặp lại đứa bạn thân ngày xưa.</div><br><div class="tuvung"><div class="viduseq">4.</div> 「お<ruby>昼<rp>（</rp><rt>ひる</rt><rp>）</rp></ruby>ごはんを<ruby>用意<rp>（</rp><rt>ようい</rt><rp>）</rp></ruby>しましたので、<ruby>召<rp>（</rp><rt>め</rt><rp>）</rp></ruby>し<ruby>上<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>がってください」「では、せっかくですから、いただきます」</div><div class="nghiavidu">"Tôi đã chuẩn bị cơm trưa rồi, mời anh dùng""Chị đã vất vả rồi, tôi xin nhận"</div></div></div></div><div class="newline"></div>`]
},

{
code: "c2",
name: "bai 2",
audiourl: './audio/cd2/40 Track 40.mp3',
cotent: [`<div class="boxtv"><div class="tuvung">1104. <b><ruby>生憎<rp>（</rp><rt>あいにく</rt><rp>）</rp></ruby></b></div><div class="hanviet3">sinh tăng  </div>

<div class="nghia3">đáng tiếc</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>古<rp>（</rp><rt>ふる</rt><rp>）</rp></ruby>い<ruby>友人<rp>（</rp><rt>ゆうじん</rt><rp>）</rp></ruby>に<ruby>電話<rp>（</rp><rt>でんわ</rt><rp>）</rp></ruby>をかけたが、あいにく<ruby>彼女<rp>（</rp><rt>かのじょ</rt><rp>）</rp></ruby>は<ruby>留守<rp>（</rp><rt>るす</rt><rp>）</rp></ruby>だった。</div><div class="nghiavidu">Gọi điện đến nhà bạn thân nhưng tiếc là cô ấy vắng nhà.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「コンサートのチケットがあるんですけど」「あいにくその<ruby>日<rp>（</rp><rt>ひ</rt><rp>）</rp></ruby>は<ruby>都合<rp>（</rp><rt>つごう</rt><rp>）</rp></ruby>が<ruby>悪<rp>（</rp><rt>わる</rt><rp>）</rp></ruby>くて…」</div><div class="nghiavidu">"Tôi có vé xem buổi hòa nhạc""Tiếc quá, hôm đó tôi bận rồi"</div><br><div class="tuvung"><div class="viduseq">3.</div> あいにくの<ruby>雨<rp>（</rp><rt>あめ</rt><rp>）</rp></ruby>だったが、<ruby>旅行<rp>（</rp><rt>りょこう</rt><rp>）</rp></ruby>は<ruby>楽<rp>（</rp><rt>たの</rt><rp>）</rp></ruby>しかった。</div><div class="nghiavidu">Tiếc là trời mưa nhưng chuyến du lịch đã rất vui.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1105. <b><ruby>案<rp>（</rp><rt>あん</rt><rp>）</rp></ruby>の<ruby>定<rp>（</rp><rt>じょう</rt><rp>）</rp></ruby></b></div><div class="hanviet3">án định  </div>

<div class="nghia3">như mong đợi</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>怪<rp>（</rp><rt>あや</rt><rp>）</rp></ruby>しいと<ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>っていたが、<ruby>案<rp>（</rp><rt>あん</rt><rp>）</rp></ruby>の<ruby>定<rp>（</rp><rt>じょう</rt><rp>）</rp></ruby>、<ruby>彼<rp>（</rp><rt>かれ</rt><rp>）</rp></ruby>は<ruby>犯人<rp>（</rp><rt>はんにん</rt><rp>）</rp></ruby>だった。</div><div class="nghiavidu">Tôi thấy đáng nghi rồi, quả nhiên anh ta là tội phạm.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>勝<rp>（</rp><rt>か</rt><rp>）</rp></ruby>つのは<ruby>難<rp>（</rp><rt>むずか</rt><rp>）</rp></ruby>しいと<ruby>予想<rp>（</rp><rt>よそう</rt><rp>）</rp></ruby>していたが、<ruby>結果<rp>（</rp><rt>けっか</rt><rp>）</rp></ruby>は<ruby>案<rp>（</rp><rt>あん</rt><rp>）</rp></ruby>の<ruby>定<rp>（</rp><rt>じょう</rt><rp>）</rp></ruby>だった。</div><div class="nghiavidu">Tôi cũng đoán được rằng chiến thắng là rất khó và quả nhiên kết quả như tôi nghĩ.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1106. <b>いよいよ</b></div><div class="hanviet3">   </div>

<div class="nghia3">cuối cùng, đã đến lúc, càng ngày càng</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> あしたはいよいよ<ruby>決勝戦<rp>（</rp><rt>けっしょうせん</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Cuối cùng ngày mai cũng là trận chung kết nhỉ.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> いよいよ<ruby>出発<rp>（</rp><rt>しゅっぱつ</rt><rp>）</rp></ruby>の<ruby>前日<rp>（</rp><rt>ぜんじつ</rt><rp>）</rp></ruby>となった。</div><div class="nghiavidu">Cuối cùng cũng sắp đến ngày xuất phát.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>台風<rp>（</rp><rt>たいふう</rt><rp>）</rp></ruby>が<ruby>近<rp>（</rp><rt>ちか</rt><rp>）</rp></ruby>づき、<ruby>雨<rp>（</rp><rt>あめ</rt><rp>）</rp></ruby>はいよいよ<ruby>激<rp>（</rp><rt>はげ</rt><rp>）</rp></ruby>しくなった。</div><div class="nghiavidu">Bão đến gần, mưa càng mạnh hơn.</div><br><div class="tuvung"><div class="viduseq">4.</div> <ruby>疑<rp>（</rp><rt>うたが</rt><rp>）</rp></ruby>いはいよいよ<ruby>強<rp>（</rp><rt>つよ</rt><rp>）</rp></ruby>かった。</div><div class="nghiavidu">Sự nghi ngờ càng mạnh mẽ hơn.</div><br><div class="tuvung"><div class="viduseq">5.</div> できるだけ<ruby>長<rp>（</rp><rt>なが</rt><rp>）</rp></ruby>く<ruby>一人<rp>（</rp><rt>ひとり</rt><rp>）</rp></ruby><ruby>暮<rp>（</rp><rt>ぐ</rt><rp>）</rp></ruby>らしを<ruby>続<rp>（</rp><rt>つづ</rt><rp>）</rp></ruby>けたいが、いよいよとなったら<ruby>老人<rp>（</rp><rt>ろうじん</rt><rp>）</rp></ruby>ホームに<ruby>入<rp>（</rp><rt>はい</rt><rp>）</rp></ruby>るつもりだ。</div><div class="nghiavidu">Nếu được tôi muốn kéo dài cuộc sống một mình nhưng cuối cùng cũng vào viện dưỡng lão.</div><br><div class="tuvung"><span class="lienquan">類</span> とうとう、ついに、ますます</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1107. <b><ruby>流石<rp>（</rp><rt>さすが</rt><rp>）</rp></ruby></b></div><div class="hanviet3">lưu thạch  </div>

<div class="nghia3">quả là, như dự đoán, thật đúng là</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>有名<rp>（</rp><rt>ゆうめい</rt><rp>）</rp></ruby>ブランド<ruby>品<rp>（</rp><rt>ひん</rt><rp>）</rp></ruby>だけあって、さすがに<ruby>高<rp>（</rp><rt>たか</rt><rp>）</rp></ruby>い。</div><div class="nghiavidu">Quả đúng là sản phẩm thương hiệu nổi tiếng, giá đắt thật.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>調子<rp>（</rp><rt>ちょうし</rt><rp>）</rp></ruby>が<ruby>悪<rp>（</rp><rt>わる</rt><rp>）</rp></ruby>くても<ruby>優勝<rp>（</rp><rt>ゆうしょう</rt><rp>）</rp></ruby>するとは、<ruby>中野<rp>（</rp><rt>なかの</rt><rp>）</rp></ruby><ruby>選手<rp>（</rp><rt>せんしゅ</rt><rp>）</rp></ruby>はさすがだ。</div><div class="nghiavidu">Dù sức khỏe không tốt nhưng vẫn chiến thắng đúng là tuyển thủ Nanoka.</div><br><div class="tuvung"><div class="viduseq">3.</div> 「あんなに<ruby>難<rp>（</rp><rt>むずか</rt><rp>）</rp></ruby>しい<ruby>問題<rp>（</rp><rt>もんだい</rt><rp>）</rp></ruby>が<ruby>解<rp>（</rp><rt>と</rt><rp>）</rp></ruby>けたんですか。さすがですね」</div><div class="nghiavidu">Một bài tập khó như thế này mà giải được, giỏi thật đấy.</div><br><div class="tuvung"><div class="viduseq">4.</div> この<ruby>問題<rp>（</rp><rt>もんだい</rt><rp>）</rp></ruby>は<ruby>難<rp>（</rp><rt>むずか</rt><rp>）</rp></ruby>しくて、さすがの<ruby>西川<rp>（</rp><rt>にしかわ</rt><rp>）</rp></ruby>さんにもできなかったそうだ。</div><div class="nghiavidu">Bài tập này khó quá, đến cả đứa như Nishikawa cũng không làm được nữa là.</div><br><div class="tuvung"><div class="viduseq">5.</div> <ruby>辛<rp>（</rp><rt>から</rt><rp>）</rp></ruby>いもの<ruby>好<rp>（</rp><rt>す</rt><rp>）</rp></ruby>きの<ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>でも、さすがにこのカレーは<ruby>食<rp>（</rp><rt>た</rt><rp>）</rp></ruby>べきれなかった。</div><div class="nghiavidu">Một người thích đồ cay như tôi cũng không thể nào ăn hết món cà ri cay như thế này được.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1108. <b><ruby>兎<rp>（</rp><rt>と</rt><rp>）</rp></ruby>に<ruby>角<rp>（</rp><rt>かく</rt><rp>）</rp></ruby></b></div><div class="hanviet3">thỏ giác  </div>

<div class="nghia3">dù sao, cách này hay cách khác</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> できるかどうかわからないが、とにかくやってみよう。</div><div class="nghiavidu">Có được hay không vẫn không rõ, nhưng dù sao hãy làm thử đi.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>最近<rp>（</rp><rt>さいきん</rt><rp>）</rp></ruby>とにかく<ruby>忙<rp>（</rp><rt>いそが</rt><rp>）</rp></ruby>しくて、<ruby>家族<rp>（</rp><rt>かぞく</rt><rp>）</rp></ruby>と<ruby>話<rp>（</rp><rt>はな</rt><rp>）</rp></ruby>す<ruby>時間<rp>（</rp><rt>じかん</rt><rp>）</rp></ruby>もない。</div><div class="nghiavidu">Gần đây rất bận đến cả thời gian nói chuyện với gia đình cũng không có.</div><br><div class="tuvung"><span class="lienquan">類</span> ともかく</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1109. <b><ruby>兎<rp>（</rp><rt>と</rt><rp>）</rp></ruby>も<ruby>角<rp>（</rp><rt>かく</rt><rp>）</rp></ruby></b></div><div class="hanviet3">thỏ giác  </div>

<div class="nghia3">dù sao, cách này hay cách khác</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>引<rp>（</rp><rt>ひ</rt><rp>）</rp></ruby>き<ruby>受<rp>（</rp><rt>う</rt><rp>）</rp></ruby>けてくれるかどうかわからないが、ともかく<ruby>頼<rp>（</rp><rt>たの</rt><rp>）</rp></ruby>んでみるつもりだ。</div><div class="nghiavidu">Có nhận hay không không rõ những dù sao cũng nhờ thử.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> あのタレントは、<ruby>歌<rp>（</rp><rt>うた</rt><rp>）</rp></ruby>はともかく、ダンスは<ruby>上手<rp>（</rp><rt>じょうず</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Tài năng trẻ đó không chỉ hát mà nhảy cũng rất giỏi.</div><br><div class="tuvung"><span class="lienquan">類</span> とにかく</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1110. <b>せめて</b></div><div class="hanviet3">   </div>

<div class="nghia3">ít nhất, tối thiểu là</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> せめて<ruby>日曜日<rp>（</rp><rt>にちようび</rt><rp>）</rp></ruby>くらいはゆっくり<ruby>休<rp>（</rp><rt>やす</rt><rp>）</rp></ruby>みたい。</div><div class="nghiavidu">Ít nhất thì cũng muốn chủ nhật được nghỉ ngơi.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>会<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>えないときは、せめて<ruby>声<rp>（</rp><rt>こえ</rt><rp>）</rp></ruby>だけでも<ruby>聞<rp>（</rp><rt>き</rt><rp>）</rp></ruby>きたい。</div><div class="nghiavidu">Khi không thể gặp được thì ít nhất cũng muốn nghe giọng nói.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>給料<rp>（</rp><rt>きゅうりょう</rt><rp>）</rp></ruby>はせめて15<ruby>万円<rp>（</rp><rt>まんえん</rt><rp>）</rp></ruby>は<ruby>欲<rp>（</rp><rt>ほ</rt><rp>）</rp></ruby>しい。</div><div class="nghiavidu">Tôi muốn ít nhất lương cũng được 15 vạn yên.</div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>少<rp>（</rp><rt>すく</rt><rp>）</rp></ruby>なくとも</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1111. <b>せいぜい</b></div><div class="hanviet3">   </div>

<div class="nghia3">tối đa, nhiều nhất có thể</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> うちから<ruby>駅<rp>（</rp><rt>えき</rt><rp>）</rp></ruby>までは、<ruby>歩<rp>（</rp><rt>ある</rt><rp>）</rp></ruby>いてもせいぜい10<ruby>分<rp>（</rp><rt>ぷん</rt><rp>）</rp></ruby>ぐらいです。</div><div class="nghiavidu">Từ nhà đi bộ đến nhà ga tối đa mất 10 phút.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> この<ruby>仕事<rp>（</rp><rt>しごと</rt><rp>）</rp></ruby>だと、<ruby>時給<rp>（</rp><rt>じきゅう</rt><rp>）</rp></ruby>はせいぜい800<ruby>円<rp>（</rp><rt>えん</rt><rp>）</rp></ruby>ぐらいだろう。</div><div class="nghiavidu">Nếu công việc này thì tối đa khoảng 800 yên nhỉ.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1112. <b>どうせ</b></div><div class="hanviet3">   </div>

<div class="nghia3">dù cho, đằng nào thì</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> どうせ<ruby>不合格<rp>（</rp><rt>ふごうかく</rt><rp>）</rp></ruby>に<ruby>決<rp>（</rp><rt>き</rt><rp>）</rp></ruby>まっているが、やっぱり<ruby>受<rp>（</rp><rt>う</rt><rp>）</rp></ruby>けたい。</div><div class="nghiavidu">Dù cho biết không đậu nhưng vẫn muốn dự thi.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> どうせ<ruby>遅刻<rp>（</rp><rt>ちこく</rt><rp>）</rp></ruby>なんだから、ゆっくり<ruby>歩<rp>（</rp><rt>ある</rt><rp>）</rp></ruby>いて<ruby>行<rp>（</rp><rt>い</rt><rp>）</rp></ruby>こう。</div><div class="nghiavidu">Đằng nào cũng trể rồi nên hãy đi thông thả thôi.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1113. <b>ぎっしり</b></div><div class="hanviet3">   </div>

<div class="nghia3">lèn chặt, đầy chặt, kín lịch</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>本棚<rp>（</rp><rt>ほんだな</rt><rp>）</rp></ruby>には<ruby>本<rp>（</rp><rt>ほん</rt><rp>）</rp></ruby>がぎっしり<ruby>並<rp>（</rp><rt>なら</rt><rp>）</rp></ruby>んでいる。</div><div class="nghiavidu">Sách xếp chật ních trên giá sách.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>来週<rp>（</rp><rt>らいしゅう</rt><rp>）</rp></ruby>はスケジュールがぎっしり｛だ/<ruby>詰<rp>（</rp><rt>つ</rt><rp>）</rp></ruby>まっている｝。</div><div class="nghiavidu">Tuần sau lịch kin mít.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1114. <b>ずらりと</b></div><div class="hanviet3">   </div>

<div class="nghia3">trong một dãy</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>息子<rp>（</rp><rt>むすこ</rt><rp>）</rp></ruby>の<ruby>本棚<rp>（</rp><rt>ほんだな</rt><rp>）</rp></ruby>にはずらりと<ruby>漫画<rp>（</rp><rt>まんが</rt><rp>）</rp></ruby>が<ruby>並<rp>（</rp><rt>なら</rt><rp>）</rp></ruby>んでいる。</div><div class="nghiavidu">Đứa con trai xếp truyện tranh một hàng trên giá sách.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>洋服<rp>（</rp><rt>ようふく</rt><rp>）</rp></ruby>ダンスには<ruby>流行<rp>（</rp><rt>りゅうこう</rt><rp>）</rp></ruby>の<ruby>服<rp>（</rp><rt>ふく</rt><rp>）</rp></ruby>がずらりと<ruby>掛<rp>（</rp><rt>か</rt><rp>）</rp></ruby>けてあった。</div><div class="nghiavidu">Quần áo nhảy phương Tây được xếp trong hàng trang phục thịnh hành.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1115. <b>あっさり</b></div><div class="hanviet3">   </div>

<div class="nghia3">đơn giản, nhẹ nhàng</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>今日<rp>（</rp><rt>きょう</rt><rp>）</rp></ruby>は<ruby>食欲<rp>（</rp><rt>しょくよく</rt><rp>）</rp></ruby>がないので、あっさりしたものが<ruby>食<rp>（</rp><rt>た</rt><rp>）</rp></ruby>べたい。</div><div class="nghiavidu">Hôm nay không muốn ăn nên chỉ ăn những thứ đơn giản thôi.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> あっさりした｛<ruby>味<rp>（</rp><rt>あじ</rt><rp>）</rp></ruby>/デザイン/<ruby>性格<rp>（</rp><rt>せいかく</rt><rp>）</rp></ruby>…｝</div><div class="nghiavidu"></div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>上司<rp>（</rp><rt>じょうし</rt><rp>）</rp></ruby>は<ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>の<ruby>安定<rp>（</rp><rt>あんてい</rt><rp>）</rp></ruby>に<ruby>反対<rp>（</rp><rt>はんたい</rt><rp>）</rp></ruby>するかと<ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>ったが、あっさり<ruby>認<rp>（</rp><rt>みと</rt><rp>）</rp></ruby>めてくれた。</div><div class="nghiavidu">Tôi nghĩ là giám đốc sẽ phản đối với đảm bảo của tôi nhưng đã nhẹ nhàng xác nhận.</div><br><div class="tuvung"><span class="lienquan">対</span> しつこい、こってり</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1116. <b>しんと・しいんと</b></div><div class="hanviet3">   </div>

<div class="nghia3">yên lặng, lặng lẽ</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>先生<rp>（</rp><rt>せんせい</rt><rp>）</rp></ruby>が<ruby>大声<rp>（</rp><rt>おおごえ</rt><rp>）</rp></ruby>で<ruby>怒<rp>（</rp><rt>おこ</rt><rp>）</rp></ruby>ると、<ruby>子供<rp>（</rp><rt>こども</rt><rp>）</rp></ruby>たちはしいんとなった。</div><div class="nghiavidu">Giáo viên nổi giận hét lớn lên thì cả lớp im như tờ.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> みんな<ruby>出<rp>（</rp><rt>で</rt><rp>）</rp></ruby>かけているらしく、<ruby>家<rp>（</rp><rt>いえ</rt><rp>）</rp></ruby>の<ruby>中<rp>（</rp><rt>なか</rt><rp>）</rp></ruby>はしいんとしていた。</div><div class="nghiavidu">Có vẻ mọi người đi vắng, bên trong nhà yên lặng.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1117. <b>ちゃんと</b></div><div class="hanviet3">   </div>

<div class="nghia3">nghiêm túc, cẩn thận, tuyệt đối</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> 「<ruby>面接<rp>（</rp><rt>めんせつ</rt><rp>）</rp></ruby>にはちゃんとした<ruby>服<rp>（</rp><rt>ふく</rt><rp>）</rp></ruby>を<ruby>着<rp>（</rp><rt>き</rt><rp>）</rp></ruby>ていくこと」</div><div class="nghiavidu">Khi đi phỏng vấn nên ăn mặc chỉnh tề.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> ちゃんとした｛<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>/<ruby>仕事<rp>（</rp><rt>しごと</rt><rp>）</rp></ruby>/<ruby>考<rp>（</rp><rt>かんが</rt><rp>）</rp></ruby>え…｝</div><div class="nghiavidu"></div><br><div class="tuvung"><div class="viduseq">3.</div> 「<ruby>部屋<rp>（</rp><rt>へや</rt><rp>）</rp></ruby>に<ruby>入<rp>（</rp><rt>はい</rt><rp>）</rp></ruby>る<ruby>時<rp>（</rp><rt>とき</rt><rp>）</rp></ruby>は、ちゃんと<ruby>挨拶<rp>（</rp><rt>あいさつ</rt><rp>）</rp></ruby>しなさい」</div><div class="nghiavidu">Khi vào phòng thì hãy chào hỏi đàng hoàng.</div><br><div class="tuvung"><div class="viduseq">4.</div> 「ちゃんとご<ruby>飯<rp>（</rp><rt>はん</rt><rp>）</rp></ruby><ruby>食<rp>（</rp><rt>た</rt><rp>）</rp></ruby>べてる？」</div><div class="nghiavidu">Con có ăn cơm đúng bữa không?</div><br><div class="tuvung"><div class="viduseq">5.</div> ちゃんと<ruby>生活<rp>（</rp><rt>せいかつ</rt><rp>）</rp></ruby>できる<ruby>給料<rp>（</rp><rt>きゅうりょう</rt><rp>）</rp></ruby>が<ruby>欲<rp>（</rp><rt>ほ</rt><rp>）</rp></ruby>しい。</div><div class="nghiavidu">Tôi muốn đồng lương có thể có cuộc sống tử tế.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1118. <b><ruby>続々<rp>（</rp><rt>ぞくぞく</rt><rp>）</rp></ruby></b></div><div class="hanviet3">tục   </div>

<div class="nghia3">liên tục, cái này sau cái kia</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>客<rp>（</rp><rt>きゃく</rt><rp>）</rp></ruby>が<ruby>続々<rp>（</rp><rt>ぞくぞく</rt><rp>）</rp></ruby>と<ruby>詰<rp>（</rp><rt>つ</rt><rp>）</rp></ruby>めかけ、<ruby>会場<rp>（</rp><rt>かいじょう</rt><rp>）</rp></ruby>はすぐに<ruby>満員<rp>（</rp><rt>まんいん</rt><rp>）</rp></ruby>になった。</div><div class="nghiavidu">Khách liên tục vào ngay lập tức hội trường đã chật người.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>新聞<rp>（</rp><rt>しんぶん</rt><rp>）</rp></ruby>に<ruby>広告<rp>（</rp><rt>こうこく</rt><rp>）</rp></ruby>が<ruby>載<rp>（</rp><rt>の</rt><rp>）</rp></ruby>ると、<ruby>続々<rp>（</rp><rt>ぞくぞく</rt><rp>）</rp></ruby>と<ruby>注文<rp>（</rp><rt>ちゅうもん</rt><rp>）</rp></ruby>が<ruby>来<rp>（</rp><rt>き</rt><rp>）</rp></ruby>た。</div><div class="nghiavidu">Khi trên báo đăng tải báo cáo thì liên tục được đặt mua.</div><br><div class="tuvung"><span class="lienquan">関</span> <ruby>次々<rp>（</rp><rt>つぎつぎ</rt><rp>）</rp></ruby></div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`]
},

{
code: "c3",
name: "bai 3",
audiourl: './audio/cd2/41 Track 41.mp3',
cotent: [`<div class="boxtv"><div class="tuvung">1119. <b>どっと</b></div><div class="hanviet3">   </div>

<div class="nghia3">tất cả cùng lúc, bất thình lình, bất chợt</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> その<ruby>冗談<rp>（</rp><rt>じょうだん</rt><rp>）</rp></ruby>を<ruby>聞<rp>（</rp><rt>き</rt><rp>）</rp></ruby>いて、<ruby>人々<rp>（</rp><rt>ひとびと</rt><rp>）</rp></ruby>はどっと<ruby>笑<rp>（</rp><rt>わら</rt><rp>）</rp></ruby>った。</div><div class="nghiavidu">Khi nghe câu chuyện đùa đó, mọi người ùa lên cười.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>非常<rp>（</rp><rt>ひじょう</rt><rp>）</rp></ruby>ベルが<ruby>鳴<rp>（</rp><rt>な</rt><rp>）</rp></ruby>ると、<ruby>観客<rp>（</rp><rt>かんきゃく</rt><rp>）</rp></ruby>たちはどっと<ruby>非常<rp>（</rp><rt>ひじょう</rt><rp>）</rp></ruby><ruby>口<rp>（</rp><rt>ぐち</rt><rp>）</rp></ruby>に<ruby>押<rp>（</rp><rt>お</rt><rp>）</rp></ruby>し<ruby>寄<rp>（</rp><rt>よ</rt><rp>）</rp></ruby>せた。</div><div class="nghiavidu">Khi chuông báo hiệu kêu lên, tất cả hành khách cùng lúc chạy đến cửa thoát hiểm.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>悔<rp>（</rp><rt>くや</rt><rp>）</rp></ruby>しくて、<ruby>涙<rp>（</rp><rt>なみだ</rt><rp>）</rp></ruby>がどっとあふれた。</div><div class="nghiavidu">Hối tiếc nên nước mắt tuôn trào ra.</div><br><div class="tuvung"><div class="viduseq">4.</div> <ruby>家<rp>（</rp><rt>いえ</rt><rp>）</rp></ruby>に<ruby>着<rp>（</rp><rt>つ</rt><rp>）</rp></ruby>くと、<ruby>疲<rp>（</rp><rt>つか</rt><rp>）</rp></ruby>れがどっと<ruby>出<rp>（</rp><rt>で</rt><rp>）</rp></ruby>た。</div><div class="nghiavidu">Khi về đến nhà, mọi mệt mỏi được gạt bỏ hết.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1120. <b>ばったり</b></div><div class="hanviet3">   </div>

<div class="nghia3">đột nhiên (ngã), đột ngột</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>隣<rp>（</rp><rt>となり</rt><rp>）</rp></ruby>に<ruby>立<rp>（</rp><rt>た</rt><rp>）</rp></ruby>っていた<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>が<ruby>突然<rp>（</rp><rt>とつぜん</rt><rp>）</rp></ruby>ばったり<ruby>倒<rp>（</rp><rt>たお</rt><rp>）</rp></ruby>れたので<ruby>驚<rp>（</rp><rt>おどろ</rt><rp>）</rp></ruby>いた。</div><div class="nghiavidu">Tôi giật mình vì người đứng bên cạnh đột nhiên ngã xuống.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>昨日<rp>（</rp><rt>きのう</rt><rp>）</rp></ruby>、<ruby>駅<rp>（</rp><rt>えき</rt><rp>）</rp></ruby>でばったり<ruby>西田<rp>（</rp><rt>にしだ</rt><rp>）</rp></ruby>さんと<ruby>会<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>った。</div><div class="nghiavidu">Hôm qua, đột nhiên gặp Nishada tại nhà ga.</div><br><div class="tuvung"><div class="viduseq">3.</div> ライバル<ruby>会社<rp>（</rp><rt>がいしゃ</rt><rp>）</rp></ruby>が<ruby>類似<rp>（</rp><rt>るいじ</rt><rp>）</rp></ruby><ruby>品<rp>（</rp><rt>ひん</rt><rp>）</rp></ruby>を<ruby>売<rp>（</rp><rt>う</rt><rp>）</rp></ruby>り<ruby>出<rp>（</rp><rt>だ</rt><rp>）</rp></ruby>すと、<ruby>注文<rp>（</rp><rt>ちゅうもん</rt><rp>）</rp></ruby>がばったりと<ruby>止<rp>（</rp><rt>と</rt><rp>）</rp></ruby>まった。</div><div class="nghiavidu">Công ty đối thủ tung ra hàng nhái, đột nhiên bị đứng hàng.</div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>偶然<rp>（</rp><rt>ぐうぜん</rt><rp>）</rp></ruby>、ぱったり、ぴったり</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1121. <b>さっさと</b></div><div class="hanviet3">   </div>

<div class="nghia3">nhanh chóng</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> 「<ruby>早<rp>（</rp><rt>はや</rt><rp>）</rp></ruby>く<ruby>片付<rp>（</rp><rt>かたづ</rt><rp>）</rp></ruby>けたいから、さっさと<ruby>食<rp>（</rp><rt>た</rt><rp>）</rp></ruby>べて」</div><div class="nghiavidu">Muốn dọn dẹp sớm nên ăn nhanh lên.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「さっさとしないと<ruby>遅刻<rp>（</rp><rt>ちこく</rt><rp>）</rp></ruby>するよ」</div><div class="nghiavidu">Không nhanh lên là trễ đấy.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>山本<rp>（</rp><rt>やまもと</rt><rp>）</rp></ruby>さんは<ruby>自分<rp>（</rp><rt>じぶん</rt><rp>）</rp></ruby>の<ruby>仕事<rp>（</rp><rt>しごと</rt><rp>）</rp></ruby>が<ruby>終<rp>（</rp><rt>お</rt><rp>）</rp></ruby>わると、さっさと<ruby>帰<rp>（</rp><rt>かえ</rt><rp>）</rp></ruby>ってしまう。</div><div class="nghiavidu">Yamamoto vừa làm xong công việc của mình thì ra về mất.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1122. <b>さっと</b></div><div class="hanviet3">   </div>

<div class="nghia3">nhanh, đột ngột</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>がコーヒーをこぼすと、<ruby>店員<rp>（</rp><rt>てんいん</rt><rp>）</rp></ruby>がさっと<ruby>拭<rp>（</rp><rt>ふ</rt><rp>）</rp></ruby>いてくれた。</div><div class="nghiavidu">Tôi vừa làm đổ cà phê thì nhân viên liền lau giúp.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「ほうれん<ruby>草<rp>（</rp><rt>くさ</rt><rp>）</rp></ruby>はさっとゆでて、<ruby>水<rp>（</rp><rt>みず</rt><rp>）</rp></ruby>に<ruby>取<rp>（</rp><rt>と</rt><rp>）</rp></ruby>ってください」</div><div class="nghiavidu">Rau dền luộc nhanh rồi đổ nước ra.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>話<rp>（</rp><rt>はなし</rt><rp>）</rp></ruby>を<ruby>聞<rp>（</rp><rt>き</rt><rp>）</rp></ruby>いて、<ruby>彼<rp>（</rp><rt>かれ</rt><rp>）</rp></ruby>の<ruby>顔色<rp>（</rp><rt>かおいろ</rt><rp>）</rp></ruby>がさっと<ruby>変<rp>（</rp><rt>か</rt><rp>）</rp></ruby>わった。</div><div class="nghiavidu">Khi nghe câu chuyện thì gương mặt anh ấy thay đổi nhanh chóng.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1123. <b>すっと</b></div><div class="hanviet3">   </div>

<div class="nghia3">vươn thẳng</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>彼女<rp>（</rp><rt>かのじょ</rt><rp>）</rp></ruby>はすっと<ruby>立<rp>（</rp><rt>た</rt><rp>）</rp></ruby>ち<ruby>上<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>がって、<ruby>部屋<rp>（</rp><rt>へや</rt><rp>）</rp></ruby>を<ruby>出<rp>（</rp><rt>で</rt><rp>）</rp></ruby>ていった。</div><div class="nghiavidu">Cô ấy đứng dậy và lao ra khỏi phòng nhanh như chớp.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> このガムをかむと、<ruby>口<rp>（</rp><rt>くち</rt><rp>）</rp></ruby>の<ruby>中<rp>（</rp><rt>なか</rt><rp>）</rp></ruby>がすっとする。</div><div class="nghiavidu">Nhai kẹo cao su này sẽ thấy sảng khoái trong miệng.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>いたいことを<ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>ったら、<ruby>胸<rp>（</rp><rt>むね</rt><rp>）</rp></ruby>がすっとした。</div><div class="nghiavidu">Nếu nói ra những điều muốn nói thì sẽ cảm thấy thoải mái.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1124. <b>せっせと</b></div><div class="hanviet3">   </div>

<div class="nghia3">siêng năng, cần cù</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>彼<rp>（</rp><rt>かれ</rt><rp>）</rp></ruby>は<ruby>若<rp>（</rp><rt>わか</rt><rp>）</rp></ruby>い<ruby>時<rp>（</rp><rt>とき</rt><rp>）</rp></ruby>にせっせと<ruby>働<rp>（</rp><rt>はたら</rt><rp>）</rp></ruby>いてお<ruby>金<rp>（</rp><rt>かね</rt><rp>）</rp></ruby>をためた。</div><div class="nghiavidu">Anh ấy lúc còn trẻ đã chăm chỉ làm việc để tích góp tiền.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>働<rp>（</rp><rt>はたら</rt><rp>）</rp></ruby>き<ruby>者<rp>（</rp><rt>もの</rt><rp>）</rp></ruby>の<ruby>祖母<rp>（</rp><rt>そぼ</rt><rp>）</rp></ruby>は、いつ<ruby>見<rp>（</rp><rt>み</rt><rp>）</rp></ruby>ても、せっせと<ruby>手<rp>（</rp><rt>て</rt><rp>）</rp></ruby>を<ruby>動<rp>（</rp><rt>うご</rt><rp>）</rp></ruby>かしている。</div><div class="nghiavidu">Những người làm lụng như ông bà lúc nào cũng thấy làm việc luôn tay.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1125. <b>ざっと</b></div><div class="hanviet3">   </div>

<div class="nghia3">khoảng, nháp, qua</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> ざっと<ruby>計算<rp>（</rp><rt>けいさん</rt><rp>）</rp></ruby>したところ、10<ruby>万<rp>（</rp><rt>まん</rt><rp>）</rp></ruby><ruby>円<rp>（</rp><rt>えん</rt><rp>）</rp></ruby>ほどかかりそうだと<ruby>分<rp>（</rp><rt>わ</rt><rp>）</rp></ruby>かった。</div><div class="nghiavidu">Tính nhanh qua mà thấy tốn 10 man.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「<ruby>会議<rp>（</rp><rt>かいぎ</rt><rp>）</rp></ruby>の<ruby>前<rp>（</rp><rt>まえ</rt><rp>）</rp></ruby>に、この<ruby>資料<rp>（</rp><rt>しりょう</rt><rp>）</rp></ruby>にざっと<ruby>目<rp>（</rp><rt>め</rt><rp>）</rp></ruby>を<ruby>通<rp>（</rp><rt>とお</rt><rp>）</rp></ruby>しておいてください」</div><div class="nghiavidu">Trước khi họp, hãy nhìn sơ qua tài liệu này.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>今日<rp>（</rp><rt>きょう</rt><rp>）</rp></ruby>のお<ruby>祭<rp>（</rp><rt>まつ</rt><rp>）</rp></ruby>りには、ざっと3000<ruby>人<rp>（</rp><rt>にん</rt><rp>）</rp></ruby>ほどが<ruby>参加<rp>（</rp><rt>さんか</rt><rp>）</rp></ruby>した。</div><div class="nghiavidu">Lễ hội hôm nay có khoảng 3000 người tham gia.</div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>大<rp>（</rp><rt>おお</rt><rp>）</rp></ruby>まかに、<ruby>大<rp>（</rp><rt>おお</rt><rp>）</rp></ruby>ざっぱに、およそ、ほぼ</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1126. <b>こっそり</b></div><div class="hanviet3">   </div>

<div class="nghia3">bí mật, lén lút</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>先生<rp>（</rp><rt>せんせい</rt><rp>）</rp></ruby>に<ruby>見<rp>（</rp><rt>み</rt><rp>）</rp></ruby>つからないように、こっそりケータイのメールを<ruby>見<rp>（</rp><rt>み</rt><rp>）</rp></ruby>た。</div><div class="nghiavidu">Lén xem tin nhắn điện thoại không để giáo viên biết.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「あなたにだけこっそり<ruby>教<rp>（</rp><rt>おし</rt><rp>）</rp></ruby>えてあげる」</div><div class="nghiavidu">Tôi chỉ lén chỉ cho bạn thôi đấy.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1127. <b><ruby>生<rp>（</rp><rt>い</rt><rp>）</rp></ruby>き<ruby>生<rp>（</rp><rt>い</rt><rp>）</rp></ruby>き</b></div><div class="hanviet3">sinh sinh  </div>

<div class="nghia3">sinh động</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>彼女<rp>（</rp><rt>かのじょ</rt><rp>）</rp></ruby>は<ruby>生<rp>（</rp><rt>い</rt><rp>）</rp></ruby>き<ruby>生<rp>（</rp><rt>い</rt><rp>）</rp></ruby>きと<ruby>働<rp>（</rp><rt>はたら</rt><rp>）</rp></ruby>いている。</div><div class="nghiavidu">Cô ấy làm việc rất hăng hái.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>子供<rp>（</rp><rt>こども</rt><rp>）</rp></ruby>たちの<ruby>生<rp>（</rp><rt>い</rt><rp>）</rp></ruby>き<ruby>生<rp>（</rp><rt>い</rt><rp>）</rp></ruby>きした<ruby>表情<rp>（</rp><rt>ひょうじょう</rt><rp>）</rp></ruby>が<ruby>印象的<rp>（</rp><rt>いんしょうてき</rt><rp>）</rp></ruby>だった。</div><div class="nghiavidu">Biểu cảm hăng hái của những đứa trẻ là một ấn tượng.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1128. <b>ぼんやり</b></div><div class="hanviet3">   </div>

<div class="nghia3">lờ mờ, mơ hồ, lơ đãng</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>霧<rp>（</rp><rt>きり</rt><rp>）</rp></ruby>の<ruby>中<rp>（</rp><rt>なか</rt><rp>）</rp></ruby>に、ぼんやり<ruby>船<rp>（</rp><rt>ふね</rt><rp>）</rp></ruby>が<ruby>見<rp>（</rp><rt>み</rt><rp>）</rp></ruby>えた。</div><div class="nghiavidu">Trong sương mờ mờ ảo ảo thấy con thuyền.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>暗<rp>（</rp><rt>くら</rt><rp>）</rp></ruby>くてぼんやりとしか<ruby>見<rp>（</rp><rt>み</rt><rp>）</rp></ruby>えなかった。</div><div class="nghiavidu">Trong đêm tối chỉ có thể thấy mờ ảo.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>昔<rp>（</rp><rt>むかし</rt><rp>）</rp></ruby>のことなので、ぼんやりとしか<ruby>覚<rp>（</rp><rt>おぼ</rt><rp>）</rp></ruby>えていない。</div><div class="nghiavidu">Chuyện của ngày xưa nên chỉ còn nhớ chút mơ hồ thôi.</div><br><div class="tuvung"><div class="viduseq">4.</div> <ruby>熱<rp>（</rp><rt>ねつ</rt><rp>）</rp></ruby>で<ruby>頭<rp>（</rp><rt>あたま</rt><rp>）</rp></ruby>がぼんやりしている。</div><div class="nghiavidu">Cảm nên đầu choáng váng.</div><br><div class="tuvung"><div class="viduseq">5.</div> ぼんやり<ruby>歩<rp>（</rp><rt>ある</rt><rp>）</rp></ruby>いていて、<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>にぶつかってしまった。</div><div class="nghiavidu">Đi bộ một cách lơ đễnh nên tông phải người.</div><br><div class="tuvung"><span class="lienquan">対</span> はっきり</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1129. <b><ruby>不図<rp>（</rp><rt>ふと</rt><rp>）</rp></ruby></b></div><div class="hanviet3">bất đồ  </div>

<div class="nghia3">đột nhiên, tình cờ</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>不図<rp>（</rp><rt>ふと</rt><rp>）</rp></ruby><ruby>窓<rp>（</rp><rt>まど</rt><rp>）</rp></ruby>の<ruby>外<rp>（</rp><rt>そと</rt><rp>）</rp></ruby>を<ruby>見<rp>（</rp><rt>み</rt><rp>）</rp></ruby>ると、<ruby>雪<rp>（</rp><rt>ゆき</rt><rp>）</rp></ruby>が<ruby>降<rp>（</rp><rt>ふ</rt><rp>）</rp></ruby>っていた。</div><div class="nghiavidu">Đột nhiên nhìn ra bên ngoài thì thấy tuyết rơi.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>不図<rp>（</rp><rt>ふと</rt><rp>）</rp></ruby>したことから、<ruby>星<rp>（</rp><rt>ほし</rt><rp>）</rp></ruby>に<ruby>興味<rp>（</rp><rt>きょうみ</rt><rp>）</rp></ruby>を<ruby>持<rp>（</rp><rt>も</rt><rp>）</rp></ruby>つようになった。</div><div class="nghiavidu">Sau một chuyện ngẫu nhiên tôi đã có hứng thú với những vì sao.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1130. <b><ruby>直<rp>（</rp><rt>じか</rt><rp>）</rp></ruby>に</b></div><div class="hanviet3">trực   </div>

<div class="nghia3">trực tiếp</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>何<rp>（</rp><rt>なに</rt><rp>）</rp></ruby>も<ruby>敷<rp>（</rp><rt>し</rt><rp>）</rp></ruby>かないで、<ruby>直<rp>（</rp><rt>じか</rt><rp>）</rp></ruby>に<ruby>地面<rp>（</rp><rt>じめん</rt><rp>）</rp></ruby>に<ruby>座<rp>（</rp><rt>すわ</rt><rp>）</rp></ruby>った。</div><div class="nghiavidu">Không phủi gì mà ngồi trực tiếp lên đất.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>社長<rp>（</rp><rt>しゃちょう</rt><rp>）</rp></ruby>と<ruby>直<rp>（</rp><rt>じか</rt><rp>）</rp></ruby>に<ruby>話<rp>（</rp><rt>はな</rt><rp>）</rp></ruby>す<ruby>機会<rp>（</rp><rt>きかい</rt><rp>）</rp></ruby>があった。</div><div class="nghiavidu">Tôi đã có cơ hội nói chuyện trực tiếp với giám đốc.</div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>直線<rp>（</rp><rt>ちょくせん</rt><rp>）</rp></ruby></div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1131. <b><ruby>一度<rp>（</rp><rt>いちど</rt><rp>）</rp></ruby>に</b></div><div class="hanviet3">nhất độ  </div>

<div class="nghia3">một lần, cùng lúc</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>一度<rp>（</rp><rt>いちど</rt><rp>）</rp></ruby>に<ruby>多<rp>（</rp><rt>おお</rt><rp>）</rp></ruby>くのことを<ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>われても、<ruby>覚<rp>（</rp><rt>おぼ</rt><rp>）</rp></ruby>えられない。</div><div class="nghiavidu">Không thể nhớ được những việc được nói cùng một lúc.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> ギョーザなどは<ruby>一度<rp>（</rp><rt>いちど</rt><rp>）</rp></ruby>にたくさん<ruby>作<rp>（</rp><rt>つく</rt><rp>）</rp></ruby>って<ruby>冷凍<rp>（</rp><rt>れいとう</rt><rp>）</rp></ruby>しておくと<ruby>便利<rp>（</rp><rt>べんり</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Món sủi cảo làm nhiều cùng một lúc rồi đông lạnh thì rất tiện lợi.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1132. <b><ruby>一斉<rp>（</rp><rt>いっせい</rt><rp>）</rp></ruby>に</b></div><div class="hanviet3">nhất tề  </div>

<div class="nghia3">cùng lúc</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> ピストルの<ruby>音<rp>（</rp><rt>おと</rt><rp>）</rp></ruby>の<ruby>同時<rp>（</rp><rt>どうじ</rt><rp>）</rp></ruby>に、<ruby>選手<rp>（</rp><rt>せんしゅ</rt><rp>）</rp></ruby>たちは<ruby>一斉<rp>（</rp><rt>いっせい</rt><rp>）</rp></ruby>にスタートした。</div><div class="nghiavidu">Đồng thời với tiếng súng, các vận động viên bắt đầu cùng lúc.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>北国<rp>（</rp><rt>きたぐに</rt><rp>）</rp></ruby>では、<ruby>春<rp>（</rp><rt>はる</rt><rp>）</rp></ruby>の<ruby>訪<rp>（</rp><rt>おとず</rt><rp>）</rp></ruby>れとともに<ruby>多<rp>（</rp><rt>おお</rt><rp>）</rp></ruby>くの<ruby>花<rp>（</rp><rt>はな</rt><rp>）</rp></ruby>が<ruby>一斉<rp>（</rp><rt>いっせい</rt><rp>）</rp></ruby>に<ruby>咲<rp>（</rp><rt>さ</rt><rp>）</rp></ruby>き<ruby>乱<rp>（</rp><rt>みだ</rt><rp>）</rp></ruby>れる。</div><div class="nghiavidu">Ở phía bắc đất nước, cùng với việc mùa xuân ghé đến là rất nhiều hoa cùng lúc nở rộ.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1133. <b><ruby>共<rp>（</rp><rt>とも</rt><rp>）</rp></ruby>に</b></div><div class="hanviet3">cộng   </div>

<div class="nghia3">cùng với</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>毎年<rp>（</rp><rt>まいねん</rt><rp>）</rp></ruby><ruby>正月<rp>（</rp><rt>しょうがつ</rt><rp>）</rp></ruby>には、<ruby>家族<rp>（</rp><rt>かぞく</rt><rp>）</rp></ruby>とともに<ruby>祖父母<rp>（</rp><rt>そふぼ</rt><rp>）</rp></ruby>の<ruby>家<rp>（</rp><rt>いえ</rt><rp>）</rp></ruby>に<ruby>行<rp>（</rp><rt>い</rt><rp>）</rp></ruby>くことになっている。</div><div class="nghiavidu">Vào dịp tết mỗi năm, gia đình sẽ về thăm nhà ông bà.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>子供<rp>（</rp><rt>こども</rt><rp>）</rp></ruby>が<ruby>生<rp>（</rp><rt>う</rt><rp>）</rp></ruby>まれた。<ruby>母子<rp>（</rp><rt>ぼし</rt><rp>）</rp></ruby>ともに<ruby>順調<rp>（</rp><rt>じゅんちょう</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Đứa con được sinh ra. Hai mẹ con đều bình an.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>娘<rp>（</rp><rt>むすめ</rt><rp>）</rp></ruby>が<ruby>結婚<rp>（</rp><rt>けっこん</rt><rp>）</rp></ruby>した。うれしいともに<ruby>寂<rp>（</rp><rt>さび</rt><rp>）</rp></ruby>しくもある。</div><div class="nghiavidu">Đứa em gái kết hôn, vui nhưng cũng kèm theo cả nỗi buồn.</div><br><div class="tuvung"><div class="viduseq">4.</div> <ruby>梅雨<rp>（</rp><rt>つゆ</rt><rp>）</rp></ruby>が<ruby>開<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>けるとともに、<ruby>気温<rp>（</rp><rt>きおん</rt><rp>）</rp></ruby>に<ruby>急<rp>（</rp><rt>きゅう</rt><rp>）</rp></ruby>に<ruby>高<rp>（</rp><rt>たか</rt><rp>）</rp></ruby>くなった。</div><div class="nghiavidu">Kết thúc mùa mưa cùng với việc nhiệt độ tăng lên đột ngột.</div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>同時<rp>（</rp><rt>どうじ</rt><rp>）</rp></ruby>に、<ruby>一緒<rp>（</rp><rt>いっしょ</rt><rp>）</rp></ruby>に</div><div class="nghiavidu"></div><br><div class="tuvung"><div class="viduseq">6.</div> <ruby>将来<rp>（</rp><rt>しょうらい</rt><rp>）</rp></ruby>、できれば<ruby>自分<rp>（</rp><rt>じぶん</rt><rp>）</rp></ruby>の<ruby>店<rp>（</rp><rt>みせ</rt><rp>）</rp></ruby>を<ruby>持<rp>（</rp><rt>も</rt><rp>）</rp></ruby>ちたい。</div><div class="nghiavidu">Tương lai, nếu được tôi muốn có một cửa hàng riêng.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1134. <b><ruby>相互<rp>（</rp><rt>そうご</rt><rp>）</rp></ruby>に</b></div><div class="hanviet3">tương/tướng hỗ  </div>

<div class="nghia3">lẫn nhau, cùng nhau</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> よく<ruby>話<rp>（</rp><rt>はな</rt><rp>）</rp></ruby>し<ruby>合<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>って、<ruby>相互<rp>（</rp><rt>そうご</rt><rp>）</rp></ruby>に<ruby>理解<rp>（</rp><rt>りかい</rt><rp>）</rp></ruby>し<ruby>合<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>うことが<ruby>大切<rp>（</rp><rt>たいせつ</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Nói chuyện nhiều với nhau thì việc hiểu nhau hơn là điều quan trọng.</div><div class="vidunotfirst"><br><div class="tuvung"><span class="lienquan">類</span> <ruby>互<rp>（</rp><rt>たが</rt><rp>）</rp></ruby>いに</div><div class="nghiavidu"></div><br><div class="tuvung"><span class="lienquan">合</span> <ruby>相互<rp>（</rp><rt>そうご</rt><rp>）</rp></ruby><ruby>理解<rp>（</rp><rt>りかい</rt><rp>）</rp></ruby></div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1135. <b><ruby>一人<rp>（</rp><rt>ひとり</rt><rp>）</rp></ruby><ruby>一人<rp>（</rp><rt>ひとり</rt><rp>）</rp></ruby></b></div><div class="hanviet3">nhất nhân nhất nhân</div>

<div class="nghia3">từng người một, lần lượt</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>出席者<rp>（</rp><rt>しゅっせきしゃ</rt><rp>）</rp></ruby>は<ruby>一人<rp>（</rp><rt>ひとり</rt><rp>）</rp></ruby><ruby>一人<rp>（</rp><rt>ひとり</rt><rp>）</rp></ruby><ruby>意見<rp>（</rp><rt>いけん</rt><rp>）</rp></ruby>を<ruby>述<rp>（</rp><rt>の</rt><rp>）</rp></ruby>べた。</div><div class="nghiavidu">Những người tham gia từng người một phát biểu ý kiến.</div><div class="vidunotfirst"><br><div class="tuvung"><span class="lienquan">類</span> めいめい、それぞれ</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1136. <b>いちいち</b></div><div class="hanviet3">   </div>

<div class="nghia3">từng thứ một, chi tiết</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>母<rp>（</rp><rt>はは</rt><rp>）</rp></ruby>は<ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>のすることにいちいち<ruby>文句<rp>（</rp><rt>もんく</rt><rp>）</rp></ruby>を<ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>う。</div><div class="nghiavidu">Mẹ phàn nàn về từng việc tôi làm.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>課長<rp>（</rp><rt>かちょう</rt><rp>）</rp></ruby>は<ruby>細<rp>（</rp><rt>こま</rt><rp>）</rp></ruby>かいこともいちいち<ruby>報告<rp>（</rp><rt>ほうこく</rt><rp>）</rp></ruby>させないと<ruby>気<rp>（</rp><rt>き</rt><rp>）</rp></ruby>がすまないようだ。</div><div class="nghiavidu">Trưởng phòng dù là những chuyện nhỏ cũng bắt báo cáo thật là không ưa chút nào.</div></div></div></div><div class="newline"></div>`]
},

{
code: "c4",
name: "bai 4",
audiourl: './audio/cd2/42 Track 42.mp3',
cotent: [`<div class="boxtv"><div class="tuvung">1137. <b><ruby>所々<rp>（</rp><rt>ところどころ</rt><rp>）</rp></ruby></b></div><div class="hanviet3">sở   </div>

<div class="nghia3">đây đó</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>地震<rp>（</rp><rt>じしん</rt><rp>）</rp></ruby>で、<ruby>併<rp>（</rp><rt>へい</rt><rp>）</rp></ruby>が<ruby>所々<rp>（</rp><rt>ところどころ</rt><rp>）</rp></ruby><ruby>崩<rp>（</rp><rt>くず</rt><rp>）</rp></ruby>れた。</div><div class="nghiavidu">Do động đất mà hàng rào đổ vỡ khắp nơi.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> この<ruby>本<rp>（</rp><rt>ほん</rt><rp>）</rp></ruby>は<ruby>所々<rp>（</rp><rt>ところどころ</rt><rp>）</rp></ruby>に<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>き<ruby>込<rp>（</rp><rt>こ</rt><rp>）</rp></ruby>みがある。</div><div class="nghiavidu">Quyển sách này có viết vào chổ này chổ kia</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1138. <b>どうか</b></div><div class="hanviet3">   </div>

<div class="nghia3">làm ơn</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> 「どうかよろしくお<ruby>願<rp>（</rp><rt>ねが</rt><rp>）</rp></ruby>いします」</div><div class="nghiavidu">Dù sao thì cũng mong anh/ chị giúp đỡ.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「どうか<ruby>今年<rp>（</rp><rt>ことし</rt><rp>）</rp></ruby>こそ<ruby>合格<rp>（</rp><rt>ごうかく</rt><rp>）</rp></ruby>できるように」</div><div class="nghiavidu">Dù sao thì cũng muốn năm nay phải đỗ.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>暑<rp>（</rp><rt>あつ</rt><rp>）</rp></ruby>くてどうかなりそうだ。</div><div class="nghiavidu">Cái nóng dường như đã bắt đầu.</div><br><div class="tuvung"><div class="viduseq">4.</div> あんなにいい<ruby>話<rp>（</rp><rt>はなし</rt><rp>）</rp></ruby>を<ruby>断<rp>（</rp><rt>ことわ</rt><rp>）</rp></ruby>るなんて、｛どうかと<ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>う/どうかしている｝。</div><div class="nghiavidu">Một chuyện tốt như thế này mà từ chối, nghĩ sao thế nhỉ.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1139. <b>できれば・できたら</b></div><div class="hanviet3">   </div>

<div class="nghia3">nếu có thể</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> 「この<ruby>事件<rp>（</rp><rt>じけん</rt><rp>）</rp></ruby>、できたら<ruby>今日<rp>（</rp><rt>きょう</rt><rp>）</rp></ruby><ruby>中<rp>（</rp><rt>じゅう</rt><rp>）</rp></ruby>にお<ruby>願<rp>（</rp><rt>ねが</rt><rp>）</rp></ruby>いします」</div><div class="nghiavidu">Vụ việc này, nếu được nhờ anh trong ngày hôm nay.</div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1140. <b>たいして</b></div><div class="hanviet3">   </div>

<div class="nghia3">không thú vị lắm</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> その<ruby>映画<rp>（</rp><rt>えいが</rt><rp>）</rp></ruby>が<ruby>面白<rp>（</rp><rt>おもしろ</rt><rp>）</rp></ruby>いと<ruby>聞<rp>（</rp><rt>き</rt><rp>）</rp></ruby>いて<ruby>見<rp>（</rp><rt>み</rt><rp>）</rp></ruby>に<ruby>行<rp>（</rp><rt>い</rt><rp>）</rp></ruby>ったのだが、たいして<ruby>面白<rp>（</rp><rt>おもしろ</rt><rp>）</rp></ruby>くなかった。</div><div class="nghiavidu">Nghe nói bộ phim đó thú vị nên đi xem nhưng mà không thú vị lắm.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「<ruby>大変<rp>（</rp><rt>たいへん</rt><rp>）</rp></ruby>ですか」「いいえ、たいして<ruby>時間<rp>（</rp><rt>じかん</rt><rp>）</rp></ruby>がかかりませんでした」</div><div class="nghiavidu">"Vất vả không?""Không ạ, không mất nhiều thời gian lắm"</div><br><div class="tuvung"><span class="lienquan">関</span> <ruby>大<rp>（</rp><rt>たい</rt><rp>）</rp></ruby>した</div><div class="nghiavidu"></div><br><div class="tuvung"><span class="lienquan">類</span> それほど</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1141. <b><ruby>恐<rp>（</rp><rt>おそ</rt><rp>）</rp></ruby>らく</b></div><div class="hanviet3">khủng   </div>

<div class="nghia3">có lẽ</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>大学<rp>（</rp><rt>だいがく</rt><rp>）</rp></ruby>に<ruby>行<rp>（</rp><rt>い</rt><rp>）</rp></ruby>かないと<ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>ったら、<ruby>父<rp>（</rp><rt>ちち</rt><rp>）</rp></ruby>は<ruby>恐<rp>（</rp><rt>おそ</rt><rp>）</rp></ruby>らく<ruby>反対<rp>（</rp><rt>はんたい</rt><rp>）</rp></ruby>するだろう。</div><div class="nghiavidu">Nếu nói không đi học đại học e là bố sẽ phản đối.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> この<ruby>動物<rp>（</rp><rt>どうぶつ</rt><rp>）</rp></ruby>は<ruby>恐<rp>（</rp><rt>おそ</rt><rp>）</rp></ruby>らく<ruby>数<rp>（</rp><rt>すう</rt><rp>）</rp></ruby><ruby>十年<rp>（</rp><rt>じゅうねん</rt><rp>）</rp></ruby>のうちに<ruby>絶滅<rp>（</rp><rt>ぜつめつ</rt><rp>）</rp></ruby>するのではないかと<ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>われる。</div><div class="nghiavidu">Loại động vật này e là đã tuyệt chủng từ vài thập kỉ trước.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1142. <b>むしろ</b></div><div class="hanviet3">   </div>

<div class="nghia3">hơn</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>寒<rp>（</rp><rt>さむ</rt><rp>）</rp></ruby>さより、むしろ<ruby>暑<rp>（</rp><rt>あつ</rt><rp>）</rp></ruby>さの<ruby>方<rp>（</rp><rt>ほう</rt><rp>）</rp></ruby>が<ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>には<ruby>耐<rp>（</rp><rt>た</rt><rp>）</rp></ruby>え<ruby>難<rp>（</rp><rt>がた</rt><rp>）</rp></ruby>い。</div><div class="nghiavidu">Tôi chịu nóng kém hơn chịu lạnh.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>黒田<rp>（</rp><rt>くろだ</rt><rp>）</rp></ruby>さんに<ruby>頼<rp>（</rp><rt>たの</rt><rp>）</rp></ruby>むくらいなら、むしろ<ruby>自分<rp>（</rp><rt>じぶん</rt><rp>）</rp></ruby>でやった<ruby>方<rp>（</rp><rt>ほう</rt><rp>）</rp></ruby>がましだ。</div><div class="nghiavidu">Nếu nhờ Kuroda thì thà tôi tự làm còn hơn.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1143. <b><ruby>果<rp>（</rp><rt>は</rt><rp>）</rp></ruby>たして</b></div><div class="hanviet3">quả   </div>

<div class="nghia3">quả nhiên, quả thật</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> この<ruby>実験<rp>（</rp><rt>じっけん</rt><rp>）</rp></ruby>は<ruby>果<rp>（</rp><rt>は</rt><rp>）</rp></ruby>たして<ruby>成功<rp>（</rp><rt>せいこう</rt><rp>）</rp></ruby>するだろうか。</div><div class="nghiavidu">Thực nghiệm này quả nhiên là sẽ thành công đúng không.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>果<rp>（</rp><rt>は</rt><rp>）</rp></ruby>たしてどのチームが<ruby>勝<rp>（</rp><rt>か</rt><rp>）</rp></ruby>つだろうか。</div><div class="nghiavidu">Quả nhiên là đội đó sẽ chiến thắng đúng không.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>鈴木<rp>（</rp><rt>すずき</rt><rp>）</rp></ruby>さんなら<ruby>大丈夫<rp>（</rp><rt>だいじょうぶ</rt><rp>）</rp></ruby>だろうと<ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>っていたが、<ruby>果<rp>（</rp><rt>は</rt><rp>）</rp></ruby>たして<ruby>受験<rp>（</rp><rt>じゅけん</rt><rp>）</rp></ruby>した<ruby>三<rp>（</rp><rt>みっ</rt><rp>）</rp></ruby>つの<ruby>大学<rp>（</rp><rt>だいがく</rt><rp>）</rp></ruby><ruby>全部<rp>（</rp><rt>ぜんぶ</rt><rp>）</rp></ruby>に<ruby>合格<rp>（</rp><rt>ごうかく</rt><rp>）</rp></ruby>した。</div><div class="nghiavidu">Nếu là Suzuki thì tôi nghĩ là ổn rồi, quả nhiên 3 trường đại học dự thi đều đậu cả.</div><br><div class="tuvung"><div class="viduseq">4.</div> <ruby>寒気<rp>（</rp><rt>さむけ</rt><rp>）</rp></ruby>がするので<ruby>熱<rp>（</rp><rt>ねつ</rt><rp>）</rp></ruby>を<ruby>測<rp>（</rp><rt>はか</rt><rp>）</rp></ruby>ったら、<ruby>果<rp>（</rp><rt>は</rt><rp>）</rp></ruby>たして38<ruby>度<rp>（</rp><rt>ど</rt><rp>）</rp></ruby>もあった。</div><div class="nghiavidu">Cảm thấy lạnh nên lấy nhiệt kế đo, quả nhiên là 38 độ.</div><br><div class="tuvung"><span class="lienquan">関</span> いったい</div><div class="nghiavidu"></div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>案<rp>（</rp><rt>あん</rt><rp>）</rp></ruby>の<ruby>定<rp>（</rp><rt>じょう</rt><rp>）</rp></ruby></div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1144. <b>かえって</b></div><div class="hanviet3">   </div>

<div class="nghia3">ngược lại</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>遅<rp>（</rp><rt>おく</rt><rp>）</rp></ruby>れそうだったのでタクシーに<ruby>乗<rp>（</rp><rt>の</rt><rp>）</rp></ruby>ったら、<ruby>道<rp>（</rp><rt>みち</rt><rp>）</rp></ruby>が<ruby>込<rp>（</rp><rt>こ</rt><rp>）</rp></ruby>んで、かえって<ruby>時間<rp>（</rp><rt>じかん</rt><rp>）</rp></ruby>がかかってしまった。</div><div class="nghiavidu">Có vẻ muộn nên lên tắc xi đi, nhưng đường tắc, ngược lại còn tốn thời gian hơn.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>薬<rp>（</rp><rt>くすり</rt><rp>）</rp></ruby>を<ruby>飲<rp>（</rp><rt>の</rt><rp>）</rp></ruby>んだら、かえって<ruby>具合<rp>（</rp><rt>ぐあい</rt><rp>）</rp></ruby>が<ruby>悪<rp>（</rp><rt>わる</rt><rp>）</rp></ruby>くなったような<ruby>気<rp>（</rp><rt>き</rt><rp>）</rp></ruby>がする。</div><div class="nghiavidu">Uống thuốc nhưng cảm giác tình trạng xấu hơn.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1145. <b><ruby>必<rp>（</rp><rt>かなら</rt><rp>）</rp></ruby>ずしも</b></div><div class="hanviet3">tất   </div>

<div class="nghia3">không hẳn, không cần thiết</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> お<ruby>金<rp>（</rp><rt>かね</rt><rp>）</rp></ruby>があれば<ruby>幸<rp>（</rp><rt>しあわ</rt><rp>）</rp></ruby>せとは、<ruby>必<rp>（</rp><rt>かなら</rt><rp>）</rp></ruby>ずしも<ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>えないだろう。</div><div class="nghiavidu">Không thể nói rằng có tiền là có hạnh phúc.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>入社<rp>（</rp><rt>にゅうしゃ</rt><rp>）</rp></ruby><ruby>試験<rp>（</rp><rt>しけん</rt><rp>）</rp></ruby>では、<ruby>必<rp>（</rp><rt>かなら</rt><rp>）</rp></ruby>ずしも<ruby>筆記<rp>（</rp><rt>ひっき</rt><rp>）</rp></ruby><ruby>試験<rp>（</rp><rt>しけん</rt><rp>）</rp></ruby>の<ruby>成績<rp>（</rp><rt>せいせき</rt><rp>）</rp></ruby>のいい<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>が<ruby>合格<rp>（</rp><rt>ごうかく</rt><rp>）</rp></ruby>すると<ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>うわけではない。</div><div class="nghiavidu">Ở kì thi tuyển vào công ty, không nhất thiết là những người có thành tích tốt trong cuộc thi viết là đậu.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>一度<rp>（</rp><rt>いちど</rt><rp>）</rp></ruby><ruby>成功<rp>（</rp><rt>せいこう</rt><rp>）</rp></ruby>したからと<ruby>言<rp>（</rp><rt>い</rt><rp>）</rp></ruby>って、<ruby>必<rp>（</rp><rt>かなら</rt><rp>）</rp></ruby>ずしも<ruby>二度目<rp>（</rp><rt>にどめ</rt><rp>）</rp></ruby>もうまくいくとは<ruby>限<rp>（</rp><rt>かぎ</rt><rp>）</rp></ruby>らない。</div><div class="nghiavidu">Nếu một lần thành công thì không hẳn là lần thứ hai cũng sẽ thành công tốt.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1146. <b><ruby>単<rp>（</rp><rt>たん</rt><rp>）</rp></ruby>に</b></div><div class="hanviet3">đơn   </div>

<div class="nghia3">chỉ, đơn giản</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>環境<rp>（</rp><rt>かんきょう</rt><rp>）</rp></ruby><ruby>問題<rp>（</rp><rt>もんだい</rt><rp>）</rp></ruby>は<ruby>単<rp>（</rp><rt>たん</rt><rp>）</rp></ruby>に<ruby>先進国<rp>（</rp><rt>せんしんこく</rt><rp>）</rp></ruby>のみの<ruby>問題<rp>（</rp><rt>もんだい</rt><rp>）</rp></ruby>ではない。</div><div class="nghiavidu">Vấn đề môi trường không đơn giản là vấn đề của các nước phát triển.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>は<ruby>単<rp>（</rp><rt>たん</rt><rp>）</rp></ruby>に<ruby>好奇心<rp>（</rp><rt>こうきしん</rt><rp>）</rp></ruby>から<ruby>聞<rp>（</rp><rt>き</rt><rp>）</rp></ruby>いてみただけだ。</div><div class="nghiavidu">Tôi chỉ đơn giản vì tính hiếu kì nên mới hỏi.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>事故<rp>（</rp><rt>じこ</rt><rp>）</rp></ruby>の<ruby>原因<rp>（</rp><rt>げんいん</rt><rp>）</rp></ruby>は<ruby>単<rp>（</rp><rt>たん</rt><rp>）</rp></ruby>なるミスだった。</div><div class="nghiavidu">Nguyên nhân của vụ tai nạn là lỗi đơn giản.</div><br><div class="tuvung"><span class="lienquan">類</span> ただ、ただの</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1147. <b>いまだに</b></div><div class="hanviet3">   </div>

<div class="nghia3">vẫn chưa</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>3日<rp>（</rp><rt>みっか</rt><rp>）</rp></ruby><ruby>前<rp>（</rp><rt>まえ</rt><rp>）</rp></ruby>に<ruby>出<rp>（</rp><rt>だ</rt><rp>）</rp></ruby>した<ruby>手紙<rp>（</rp><rt>てがみ</rt><rp>）</rp></ruby>がいまだに<ruby>着<rp>（</rp><rt>つ</rt><rp>）</rp></ruby>かないのはおかしい。</div><div class="nghiavidu">Lá thư gửi từ 3 ngày trước đến giờ vẫn chưa đến thật là kì lạ.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> あの<ruby>時<rp>（</rp><rt>とき</rt><rp>）</rp></ruby>の<ruby>悔<rp>（</rp><rt>くや</rt><rp>）</rp></ruby>しさはいまだに<ruby>忘<rp>（</rp><rt>わす</rt><rp>）</rp></ruby>れられない。</div><div class="nghiavidu">Sự hối hận lúc đó đến giờ vẫn không thể quên.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1148. <b>ついでに</b></div><div class="hanviet3">   </div>

<div class="nghia3">nhân tiện</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> 「<ruby>散歩<rp>（</rp><rt>さんぽ</rt><rp>）</rp></ruby>に<ruby>行<rp>（</rp><rt>い</rt><rp>）</rp></ruby>くんだったら、ついでにこの<ruby>手紙<rp>（</rp><rt>てがみ</rt><rp>）</rp></ruby>を<ruby>出<rp>（</rp><rt>だ</rt><rp>）</rp></ruby>してきた」</div><div class="nghiavidu">Nếu đi tản bộ thì nhân tiện gửi lá thư này với nhé.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>出張<rp>（</rp><rt>しゅっちょう</rt><rp>）</rp></ruby>で<ruby>大阪<rp>（</rp><rt>おおさか</rt><rp>）</rp></ruby>に<ruby>行<rp>（</rp><rt>い</rt><rp>）</rp></ruby>ったついでに、<ruby>親戚<rp>（</rp><rt>しんせき</rt><rp>）</rp></ruby>の<ruby>家<rp>（</rp><rt>いえ</rt><rp>）</rp></ruby>に<ruby>寄<rp>（</rp><rt>よ</rt><rp>）</rp></ruby>ってきた。</div><div class="nghiavidu">Vì công tác nên nhân tiện đến Osaka, tôi đã ghé nhà người thân.</div><br><div class="tuvung"><div class="viduseq">3.</div> 「ついでの<ruby>時<rp>（</rp><rt>とき</rt><rp>）</rp></ruby>に、これをコピーしておいてください」</div><div class="nghiavidu">Lúc tiện thì hãy phô tô cái này nhé.</div><br><div class="tuvung"><div class="viduseq">4.</div> ついでがあったので、<ruby>母<rp>（</rp><rt>はは</rt><rp>）</rp></ruby>に<ruby>頼<rp>（</rp><rt>たの</rt><rp>）</rp></ruby>まれていた<ruby>買<rp>（</rp><rt>か</rt><rp>）</rp></ruby>い<ruby>物<rp>（</rp><rt>もの</rt><rp>）</rp></ruby>をしてきた。</div><div class="nghiavidu">Tiện thể nên tôi mua hàng mà mẹ đã nhờ.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1149. <b>とりあえず</b></div><div class="hanviet3">   </div>

<div class="nghia3">đầu tiên</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>財布<rp>（</rp><rt>さいふ</rt><rp>）</rp></ruby>を<ruby>落<rp>（</rp><rt>お</rt><rp>）</rp></ruby>としてしまったので、とりあえず<ruby>警察<rp>（</rp><rt>けいさつ</rt><rp>）</rp></ruby>に<ruby>届<rp>（</rp><rt>とど</rt><rp>）</rp></ruby>けた。</div><div class="nghiavidu">Làm rơi ví mất nên tạm thời đến báo đồn cảnh sát.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>引<rp>（</rp><rt>ひ</rt><rp>）</rp></ruby>っ<ruby>越<rp>（</rp><rt>こ</rt><rp>）</rp></ruby>しの<ruby>荷造<rp>（</rp><rt>にづく</rt><rp>）</rp></ruby>りは<ruby>済<rp>（</rp><rt>す</rt><rp>）</rp></ruby>んだ。とりあえず<ruby>必要<rp>（</rp><rt>ひつよう</rt><rp>）</rp></ruby>なものはこの<ruby>箱<rp>（</rp><rt>はこ</rt><rp>）</rp></ruby>に<ruby>入<rp>（</rp><rt>はい</rt><rp>）</rp></ruby>っている。</div><div class="nghiavidu">Làm xong hàng hóa chuyển nhà, trước tiên bỏ những thứ cần thiết vào hộp.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1150. <b><ruby>万一<rp>（</rp><rt>まんいち</rt><rp>）</rp></ruby>・<ruby>万<rp>（</rp><rt>まん</rt><rp>）</rp></ruby>が<ruby>一<rp>（</rp><rt>いち</rt><rp>）</rp></ruby></b></div><div class="hanviet3">vạn nhất vạn nhất</div>

<div class="nghia3">khẩn cấp, trường hợp xấu</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>大丈夫<rp>（</rp><rt>だいじょうぶ</rt><rp>）</rp></ruby>だと<ruby>思<rp>（</rp><rt>おも</rt><rp>）</rp></ruby>うが、<ruby>万一<rp>（</rp><rt>まんいち</rt><rp>）</rp></ruby><ruby>失敗<rp>（</rp><rt>しっぱい</rt><rp>）</rp></ruby>したらどうしよう。</div><div class="nghiavidu">Tôi nghĩ là không sao nhưng trong trường hợp thất bại thì làm sao?</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>万一<rp>（</rp><rt>まんいち</rt><rp>）</rp></ruby>の<ruby>時<rp>（</rp><rt>とき</rt><rp>）</rp></ruby>のために<ruby>保険<rp>（</rp><rt>ほけん</rt><rp>）</rp></ruby>に<ruby>入<rp>（</rp><rt>はい</rt><rp>）</rp></ruby>った。</div><div class="nghiavidu">Để phòng những lúc không hay tôi tham gia bảo hiểm.</div><br><div class="tuvung"><div class="viduseq">3.</div> 「<ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>に<ruby>万一<rp>（</rp><rt>まんいち</rt><rp>）</rp></ruby>のことがあった<ruby>場合<rp>（</rp><rt>ばあい</rt><rp>）</rp></ruby>は、あの<ruby>弁護士<rp>（</rp><rt>べんごし</rt><rp>）</rp></ruby>さんに<ruby>相談<rp>（</rp><rt>そうだん</rt><rp>）</rp></ruby>しなさい」</div><div class="nghiavidu">Trường hợp có chuyện gì không hay với tôi, hãy thảo luận với vị luật sư ấy.</div><br><div class="tuvung"><span class="lienquan">類</span> もし、もしも</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1151. <b><ruby>偶然<rp>（</rp><rt>ぐうぜん</rt><rp>）</rp></ruby></b></div><div class="hanviet3">ngẫu nhiên  </div>

<div class="nghia3">ngẫu nhiên, bất ngờ</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>駅<rp>（</rp><rt>えき</rt><rp>）</rp></ruby>で<ruby>偶然<rp>（</rp><rt>ぐうぜん</rt><rp>）</rp></ruby><ruby>昔<rp>（</rp><rt>むかし</rt><rp>）</rp></ruby>の<ruby>知<rp>（</rp><rt>し</rt><rp>）</rp></ruby>り<ruby>合<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>いに<ruby>会<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>った。</div><div class="nghiavidu">Tình cờ gặp lại người quen ở nhà ga.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> この<ruby>発見<rp>（</rp><rt>はっけん</rt><rp>）</rp></ruby>はいろいろな<ruby>偶然<rp>（</rp><rt>ぐうぜん</rt><rp>）</rp></ruby>が<ruby>重<rp>（</rp><rt>かさ</rt><rp>）</rp></ruby>ねった<ruby>結果<rp>（</rp><rt>けっか</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Phát hiện này là kết quả của những sự ngẫu nhiên chồng lên nhau.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>偶然<rp>（</rp><rt>ぐうぜん</rt><rp>）</rp></ruby>のいっち</div><div class="nghiavidu">Thống nhất ngẫu nhiên.</div><br><div class="tuvung"><span class="lienquan">類</span> たまたま</div><div class="nghiavidu"></div><br><div class="tuvung"><span class="lienquan">対</span> <ruby>必然<rp>（</rp><rt>ひつぜん</rt><rp>）</rp></ruby></div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`]
},

{
code: "c5",
name: "bai 5",
audiourl: './audio/cd2/43 Track 43.mp3',
cotent: [`<div class="boxtv"><div class="tuvung">1152. <b><ruby>偶々<rp>（</rp><rt>たまたま</rt><rp>）</rp></ruby></b></div><div class="hanviet3">ngẫu   </div>

<div class="nghia3">thỉnh thoảng, hiếm, đôi khi</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> たまたま<ruby>入<rp>（</rp><rt>はい</rt><rp>）</rp></ruby>った<ruby>喫茶店<rp>（</rp><rt>きっさてん</rt><rp>）</rp></ruby>は、<ruby>友達<rp>（</rp><rt>ともだち</rt><rp>）</rp></ruby>に<ruby>会<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>った。</div><div class="nghiavidu">Gặp bạn ở quán cà phê hay vào.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> 「<ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>は<ruby>事件<rp>（</rp><rt>じけん</rt><rp>）</rp></ruby>とは<ruby>関係<rp>（</rp><rt>かんけい</rt><rp>）</rp></ruby>ありません。たまたま<ruby>通<rp>（</rp><rt>とお</rt><rp>）</rp></ruby>りかかっただけです」</div><div class="nghiavidu">Tôi không liên quan đến vụ án tôi chỉ tình cờ đi ngang qua thôi.</div><br><div class="tuvung"><span class="lienquan">類</span> <ruby>偶然<rp>（</rp><rt>ぐうぜん</rt><rp>）</rp></ruby></div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1153. <b><ruby>実際<rp>（</rp><rt>じっさい</rt><rp>）</rp></ruby></b></div><div class="hanviet3">thực tế  </div>

<div class="nghia3">thực tế, thực sự</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>簡単<rp>（</rp><rt>かんたん</rt><rp>）</rp></ruby>そうに<ruby>見<rp>（</rp><rt>み</rt><rp>）</rp></ruby>えても、<ruby>実際<rp>（</rp><rt>じっさい</rt><rp>）</rp></ruby>にやってみるとうまくできないことが<ruby>多<rp>（</rp><rt>おお</rt><rp>）</rp></ruby>い。</div><div class="nghiavidu">Nhìn có vẻ đơn giản nhưng nhiều trường hợp thực tế khi bắt tay vào làm thì không tiến triển tốt.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>働<rp>（</rp><rt>はたら</rt><rp>）</rp></ruby>きやすい<ruby>会社<rp>（</rp><rt>かいしゃ</rt><rp>）</rp></ruby>だと<ruby>聞<rp>（</rp><rt>き</rt><rp>）</rp></ruby>いて<ruby>入社<rp>（</rp><rt>にゅうしゃ</rt><rp>）</rp></ruby>したが、<ruby>実際<rp>（</rp><rt>じっさい</rt><rp>）</rp></ruby>、<ruby>社員<rp>（</rp><rt>しゃいん</rt><rp>）</rp></ruby>を<ruby>大切<rp>（</rp><rt>たいせつ</rt><rp>）</rp></ruby>にしてくれる。</div><div class="nghiavidu">Nghe nói công ty làm việc đơn giản nên xin vào nhưng thực tế thì họ quan trọng nhân viên.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>働<rp>（</rp><rt>はたら</rt><rp>）</rp></ruby>きやすい<ruby>会社<rp>（</rp><rt>かいしゃ</rt><rp>）</rp></ruby>だと<ruby>聞<rp>（</rp><rt>き</rt><rp>）</rp></ruby>いて<ruby>入社<rp>（</rp><rt>にゅうしゃ</rt><rp>）</rp></ruby>したが、<ruby>実際<rp>（</rp><rt>じっさい</rt><rp>）</rp></ruby>、<ruby>違<rp>（</rp><rt>ちが</rt><rp>）</rp></ruby>った。</div><div class="nghiavidu">Nghe nói công ty làm việc đơn giản nên xin vào nhưng thực tế thì không phải.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1154. <b><ruby>同様<rp>（</rp><rt>どうよう</rt><rp>）</rp></ruby></b></div><div class="hanviet3">đồng dạng  </div>

<div class="nghia3">giống như</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> リサイクルショップには<ruby>新品<rp>（</rp><rt>しんぴん</rt><rp>）</rp></ruby><ruby>同様<rp>（</rp><rt>どうよう</rt><rp>）</rp></ruby>の<ruby>物<rp>（</rp><rt>もの</rt><rp>）</rp></ruby>もある。</div><div class="nghiavidu">Ở trong cửa hàng tái chế cũng có cả những sản phẩm giống với sản phẩm mới.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>も｛<ruby>姉<rp>（</rp><rt>あね</rt><rp>）</rp></ruby><ruby>同様<rp>（</rp><rt>どうよう</rt><rp>）</rp></ruby>/<ruby>姉<rp>（</rp><rt>あね</rt><rp>）</rp></ruby>と<ruby>同様<rp>（</rp><rt>どうよう</rt><rp>）</rp></ruby>に｝アレルギー<ruby>体質<rp>（</rp><rt>たいしつ</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Tôi cũng có thể chất dị ứng giống chị gái tôi.</div><br><div class="tuvung"><div class="viduseq">3.</div> <ruby>日本<rp>（</rp><rt>にほん</rt><rp>）</rp></ruby>では<ruby>少子<rp>（</rp><rt>しょうし</rt><rp>）</rp></ruby><ruby>高齢化<rp>（</rp><rt>こうれいか</rt><rp>）</rp></ruby>が<ruby>進<rp>（</rp><rt>すす</rt><rp>）</rp></ruby>んでいるが、<ruby>韓国<rp>（</rp><rt>かんこく</rt><rp>）</rp></ruby>も<ruby>同様<rp>（</rp><rt>どうよう</rt><rp>）</rp></ruby>だそうだ。</div><div class="nghiavidu">Nhật Bản đang tiến đến tỉ lệ sinh giảm và sự già hóa dân số, Hàn Quốc cũng giống như vậy.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1155. <b><ruby>元々<rp>（</rp><rt>もともと</rt><rp>）</rp></ruby></b></div><div class="hanviet3">nguyên   </div>

<div class="nghia3">ban đầu, vốn dĩ</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>元々<rp>（</rp><rt>もともと</rt><rp>）</rp></ruby><ruby>体<rp>（</rp><rt>からだ</rt><rp>）</rp></ruby>が<ruby>弱<rp>（</rp><rt>よわ</rt><rp>）</rp></ruby>かったのだが、<ruby>最近<rp>（</rp><rt>さいきん</rt><rp>）</rp></ruby><ruby>一層<rp>（</rp><rt>いっそう</rt><rp>）</rp></ruby><ruby>疲<rp>（</rp><rt>つか</rt><rp>）</rp></ruby>れやすかった。</div><div class="nghiavidu">Vốn dĩ thì cơ thể đã yếu rồi nhưng gần đây thì lại càng dễ mệt hơn.</div><div class="vidunotfirst"><br><div class="tuvung"><span class="lienquan">関</span> <ruby>元<rp>（</rp><rt>もと</rt><rp>）</rp></ruby></div><div class="nghiavidu"></div><br><div class="tuvung"><span class="lienquan">慣</span> だめで<ruby>元々<rp>（</rp><rt>もともと</rt><rp>）</rp></ruby></div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1156. <b><ruby>本来<rp>（</rp><rt>ほんらい</rt><rp>）</rp></ruby></b></div><div class="hanviet3">bản lai  </div>

<div class="nghia3">từ đầu, nguyên bản</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> このビルは<ruby>本来<rp>（</rp><rt>ほんらい</rt><rp>）</rp></ruby><ruby>昨年<rp>（</rp><rt>さくねん</rt><rp>）</rp></ruby><ruby>完成<rp>（</rp><rt>かんせい</rt><rp>）</rp></ruby>の<ruby>予定<rp>（</rp><rt>よてい</rt><rp>）</rp></ruby>だったが、<ruby>資金<rp>（</rp><rt>しきん</rt><rp>）</rp></ruby><ruby>不足<rp>（</rp><rt>ぶそく</rt><rp>）</rp></ruby>でまだ<ruby>完成<rp>（</rp><rt>かんせい</rt><rp>）</rp></ruby>していない。</div><div class="nghiavidu">Tòa nhà này vốn dĩ dự tính năm ngoái hoàn thành nhưng vì thiếu vốn đầu tư nên vẫn chưa xong.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> <ruby>緊張<rp>（</rp><rt>きんちょう</rt><rp>）</rp></ruby>して、<ruby>本来<rp>（</rp><rt>ほんらい</rt><rp>）</rp></ruby>の<ruby>力<rp>（</rp><rt>ちから</rt><rp>）</rp></ruby>が<ruby>出<rp>（</rp><rt>だ</rt><rp>）</rp></ruby>せなかった。</div><div class="nghiavidu">Vì hồi hộp nên không thể để cơ thể tự nhiên được.</div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1157. <b>ある</b></div><div class="hanviet3">   </div>

<div class="nghia3">có, một số</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> ある<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>から、<ruby>近々<rp>（</rp><rt>ちかぢか</rt><rp>）</rp></ruby><ruby>人事<rp>（</rp><rt>じんじ</rt><rp>）</rp></ruby><ruby>異動<rp>（</rp><rt>いどう</rt><rp>）</rp></ruby>があると<ruby>聞<rp>（</rp><rt>き</rt><rp>）</rp></ruby>いた。</div><div class="nghiavidu">Tôi nghe từ người ấy sẽ có cải tổ chính phủ trong thời gian tới.</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> ある｛<ruby>時<rp>（</rp><rt>とき</rt><rp>）</rp></ruby>/<ruby>日<rp>（</rp><rt>ひ</rt><rp>）</rp></ruby>…｝</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1158. <b><ruby>有<rp>（</rp><rt>たもつ</rt><rp>）</rp></ruby>らゆる</b></div><div class="hanviet3">hữu   </div>

<div class="nghia3">tất cả</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> あの<ruby>博物館<rp>（</rp><rt>はくぶつかん</rt><rp>）</rp></ruby>にはあらゆる<ruby>種類<rp>（</rp><rt>しゅるい</rt><rp>）</rp></ruby>の<ruby>昆虫<rp>（</rp><rt>こんちゅう</rt><rp>）</rp></ruby>が<ruby>集<rp>（</rp><rt>あつ</rt><rp>）</rp></ruby>められている。</div><div class="nghiavidu">Viện bảo tàng nọ tập hợp rất nhiều loại côn trùng.</div><div class="vidunotfirst"><br><div class="tuvung"><span class="lienquan">連</span> ありと＿</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1159. <b><ruby>大<rp>（</rp><rt>たい</rt><rp>）</rp></ruby>した</b></div><div class="hanviet3">đại   </div>

<div class="nghia3">quan trọng, to lớn</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> 「けがの<ruby>具合<rp>（</rp><rt>ぐあい</rt><rp>）</rp></ruby>はどうですか」「<ruby>大<rp>（</rp><rt>たい</rt><rp>）</rp></ruby>したことはありません」</div><div class="nghiavidu">"Tình trạng vết thương thế nào?""Không có gì nghiêm trọng ạ"</div><div class="vidunotfirst"><br><div class="tuvung"><div class="viduseq">2.</div> この<ruby>難<rp>（</rp><rt>むずか</rt><rp>）</rp></ruby>しい<ruby>試験<rp>（</rp><rt>しけん</rt><rp>）</rp></ruby>に1<ruby>回<rp>（</rp><rt>かい</rt><rp>）</rp></ruby>で<ruby>合格<rp>（</rp><rt>ごうかく</rt><rp>）</rp></ruby>するとは、たいしたものだ。</div><div class="nghiavidu">Chỉ một lần vượt qua kì thi khó là điều rất vĩ đại.</div><br><div class="tuvung"><div class="viduseq">3.</div> あの<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>は<ruby>何<rp>（</rp><rt>なに</rt><rp>）</rp></ruby>があっても<ruby>冷静<rp>（</rp><rt>れいせい</rt><rp>）</rp></ruby>に<ruby>対処<rp>（</rp><rt>たいしょ</rt><rp>）</rp></ruby>する。<ruby>大<rp>（</rp><rt>たい</rt><rp>）</rp></ruby>した<ruby>人<rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>だ。</div><div class="nghiavidu">Người ấy dù gặp chuyện gì cũng bình tĩnh xử lí quả là người tuyệt vời.</div><br><div class="tuvung"><span class="lienquan">関</span> たいして</div><div class="nghiavidu"></div></div></div></div><div class="newline"></div>`,`<div class="boxtv"><div class="tuvung">1160. <b><ruby>所謂<rp>（</rp><rt>いわゆる</rt><rp>）</rp></ruby></b></div><div class="hanviet3">sở vị  </div>

<div class="nghia3">cái được gọi là</div><div class="vidubox"><br><div class="tuvung"><div class="viduseq">1.</div> <ruby>私<rp>（</rp><rt>わたし</rt><rp>）</rp></ruby>はいわゆる<ruby>受験<rp>（</rp><rt>じゅけん</rt><rp>）</rp></ruby><ruby>戦争<rp>（</rp><rt>せんそう</rt><rp>）</rp></ruby>とは<ruby>無縁<rp>（</rp><rt>むえん</rt><rp>）</rp></ruby>の<ruby>高校<rp>（</rp><rt>こうこう</rt><rp>）</rp></ruby><ruby>時代<rp>（</rp><rt>じだい</rt><rp>）</rp></ruby>を<ruby>過<rp>（</rp><rt>す</rt><rp>）</rp></ruby>ごした。</div><div class="nghiavidu">Tóm lại thời cấp 3, tôi không tham gia vào chạy đua thi cử.</div></div></div><div class="newline"></div>`]
},

];//var u